/**
 * SwissBrAIn PPTX Export with Source Grounding
 * Generate downloadable PowerPoint files with embedded screenshots of source passages
 */

import PptxGenJS from 'pptxgenjs';
import { toPng } from 'html-to-image';
import { StylePreset, stylePresets, getStyleConfig } from './stylePresets';

export interface SlideData {
  title: string;
  body: string;
  bullets?: string[];
  sourceSnippet?: {
    text: string;
    pageNumber: number;
    bbox?: { x: number; y: number; width: number; height: number };
    imageData?: string; // Base64 image data
  };
  speakerNotes?: string;
  layout?: 'title' | 'content' | 'section' | 'two-column';
}

export interface ExportOptions {
  theme: StylePreset;
  includeSourceSnapshots: boolean;
  includeHyperlinks: boolean;
  highDPI: boolean;
  author?: string;
  company?: string;
}

// Theme to PPTX color mapping
const themeColors: Record<StylePreset, {
  bg: string;
  title: string;
  body: string;
  accent: string;
  surface: string;
}> = {
  corporate: { bg: '1e293b', title: 'FFFFFF', body: 'd1d5db', accent: '3b82f6', surface: 'f8fafc' },
  creative: { bg: '7c3aed', title: 'FFFFFF', body: 'fce7f3', accent: 'f59e0b', surface: 'faf5ff' },
  academic: { bg: '065f46', title: 'FFFFFF', body: 'd1fae5', accent: 'd97706', surface: 'fffbeb' },
  minimal: { bg: 'FFFFFF', title: '18181b', body: '52525b', accent: '18181b', surface: 'fafafa' },
  narrative: { bg: '831843', title: 'FFFFFF', body: 'fce7f3', accent: 'fbbf24', surface: 'fef3c7' },
};

/**
 * Capture a DOM element as a base64 PNG image
 */
export async function captureSourceSnippet(
  element: HTMLElement, 
  highDPI: boolean = true
): Promise<string> {
  return await toPng(element, {
    quality: 1,
    pixelRatio: highDPI ? 2 : 1,
    backgroundColor: '#ffffff',
    cacheBust: true,
  });
}

/**
 * Normalize coordinates from percentage-based to slide inches
 */
export function normalizeCoordinates(
  bbox: { x: number; y: number; width: number; height: number },
  pageSize: { width: number; height: number },
  slideSize: { width: number; height: number }
): { x: number; y: number; w: number; h: number } {
  const xRatio = slideSize.width / pageSize.width;
  const yRatio = slideSize.height / pageSize.height;
  
  return {
    x: (bbox.x / 100) * slideSize.width,
    y: (bbox.y / 100) * slideSize.height,
    w: (bbox.width / 100) * slideSize.width,
    h: (bbox.height / 100) * slideSize.height,
  };
}

/**
 * Export slides to PPTX with optional source snapshots
 */
export async function exportToPptx(
  slides: SlideData[],
  title: string,
  options: ExportOptions
): Promise<Blob> {
  const pres = new PptxGenJS();
  const colors = themeColors[options.theme];
  
  // Presentation metadata
  pres.author = options.author || 'SwissBrAIn Studio';
  pres.company = options.company || 'SwissBrAIn';
  pres.title = title;
  pres.subject = 'AI-Generated Presentation';
  pres.layout = 'LAYOUT_WIDE'; // 16:9

  // Create title slide
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: colors.bg };
  
  // Accent bar
  titleSlide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 0.15,
    h: '100%',
    fill: { color: colors.accent },
  });
  
  // Main title
  titleSlide.addText(title, {
    x: 1,
    y: 2.5,
    w: '85%',
    fontSize: 54,
    bold: true,
    color: colors.title,
    fontFace: 'Inter',
  });
  
  // Subtitle
  titleSlide.addText('Generated by SwissBrAIn Studio', {
    x: 1,
    y: 4,
    w: '85%',
    fontSize: 18,
    color: colors.body,
    fontFace: 'Inter',
  });

  // Content slides
  for (let i = 0; i < slides.length; i++) {
    const slideData = slides[i];
    const slide = pres.addSlide();
    slide.background = { color: colors.bg };

    // Accent bar
    slide.addShape(pres.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 0.15,
      h: '100%',
      fill: { color: colors.accent },
    });

    // Determine layout based on source snapshot
    const hasSource = slideData.sourceSnippet && options.includeSourceSnapshots;
    
    if (hasSource && slideData.sourceSnippet?.imageData) {
      // Two-column layout: Source on left, content on right
      
      // Source snapshot (left side - 45%)
      slide.addImage({
        data: slideData.sourceSnippet.imageData,
        x: 0.5,
        y: 1.5,
        w: 4.5,
        h: 3.5,
      });
      
      // Source citation
      slide.addText(`Source: Page ${slideData.sourceSnippet.pageNumber}`, {
        x: 0.5,
        y: 5.1,
        w: 4.5,
        fontSize: 10,
        color: colors.body,
        fontFace: 'Inter',
      });
      
      // Title (right side)
      slide.addText(slideData.title, {
        x: 5.5,
        y: 0.5,
        w: 7,
        fontSize: 32,
        bold: true,
        color: colors.title,
        fontFace: 'Inter',
      });
      
      // Body text (right side)
      if (slideData.bullets && slideData.bullets.length > 0) {
        slide.addText(
          slideData.bullets.map(b => ({ text: b, options: { bullet: true } })),
          {
            x: 5.5,
            y: 1.5,
            w: 7,
            h: 4,
            fontSize: 16,
            color: colors.body,
            fontFace: 'Inter',
            valign: 'top',
          }
        );
      } else if (slideData.body) {
        slide.addText(slideData.body, {
          x: 5.5,
          y: 1.5,
          w: 7,
          h: 4,
          fontSize: 16,
          color: colors.body,
          fontFace: 'Inter',
          valign: 'top',
        });
      }
    } else {
      // Standard layout
      
      // Section header slide
      if (slideData.layout === 'section') {
        slide.addText(slideData.title, {
          x: 1,
          y: 2.3,
          w: '85%',
          fontSize: 44,
          bold: true,
          color: colors.title,
          fontFace: 'Inter',
        });
        
        if (slideData.body) {
          slide.addText(slideData.body, {
            x: 1,
            y: 3.5,
            w: '85%',
            fontSize: 20,
            color: colors.body,
            fontFace: 'Inter',
          });
        }
      } else {
        // Standard content slide
        slide.addText(slideData.title, {
          x: 0.5,
          y: 0.5,
          w: '90%',
          fontSize: 36,
          bold: true,
          color: colors.title,
          fontFace: 'Inter',
        });
        
        if (slideData.bullets && slideData.bullets.length > 0) {
          slide.addText(
            slideData.bullets.map(b => ({ text: b, options: { bullet: true } })),
            {
              x: 0.5,
              y: 1.5,
              w: '90%',
              h: 4,
              fontSize: 18,
              color: colors.body,
              fontFace: 'Inter',
              valign: 'top',
            }
          );
        } else if (slideData.body) {
          slide.addText(slideData.body, {
            x: 0.5,
            y: 1.5,
            w: '90%',
            h: 4,
            fontSize: 18,
            color: colors.body,
            fontFace: 'Inter',
            valign: 'top',
          });
        }
      }
    }

    // Speaker notes
    if (slideData.speakerNotes) {
      slide.addNotes(slideData.speakerNotes);
    }
  }

  // Generate blob
  const data = await pres.write({ outputType: 'blob' });
  return data as Blob;
}

/**
 * Download PPTX file
 */
export async function downloadPptx(
  slides: SlideData[],
  title: string,
  options: ExportOptions
): Promise<void> {
  const blob = await exportToPptx(slides, title, options);
  
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/[^a-zA-Z0-9]/g, '_')}_${options.theme}.pptx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Convert artifact slides to export format
 */
export function convertToSlideData(
  slides: Array<{
    number?: number;
    layout?: string;
    title: string;
    subtitle?: string;
    bullets?: string[];
    notes?: string;
    content?: string;
  }>,
  sourceChunks?: Array<{
    source_id: string;
    title: string;
    text: string;
    page_number?: number;
  }>
): SlideData[] {
  return slides.map((slide, index) => {
    const sourceSnippet = sourceChunks?.[index];
    
    return {
      title: slide.title,
      body: slide.content || slide.subtitle || '',
      bullets: slide.bullets,
      speakerNotes: slide.notes,
      layout: (slide.layout as 'title' | 'content' | 'section') || 'content',
      sourceSnippet: sourceSnippet ? {
        text: sourceSnippet.text,
        pageNumber: sourceSnippet.page_number || 1,
      } : undefined,
    };
  });
}

export default {
  exportToPptx,
  downloadPptx,
  captureSourceSnippet,
  normalizeCoordinates,
  convertToSlideData,
};
