// Centralized icon barrel - all icons must be imported from here
// This file re-exports everything from lucide-react to ensure consistent imports
export * from "lucide-react";

// Tabler → Lucide aliases (compat layer, so refactors are mechanical)
export {
  Search as IconSearch,
  ArrowRight as IconArrowRight,
  Loader2 as IconLoader2,
  ExternalLink as IconExternalLink,
  TrendingUp as IconTrendingUp,
  Bell as IconBell,
  Brain as IconBrain,
  Lightbulb as IconBulb,
  Scale as IconScale,
  BookOpen as IconBook2,
  GraduationCap as IconSchool,
  Shield as IconShield,
  ShieldCheck as IconShieldCheck,
  Plane as IconPlane,
  Activity as IconActivity,
  Compass as IconCompass,
  TestTube as IconTestPipe,
  Files as IconFileStack,
  FileText as IconFileDescription,
  FileSearch as IconFileSearch,
  LayoutGrid as IconChartTreemap,
  FlaskConical as IconFlask,
  Globe as IconWorld,
  Plus as IconPlus,
  MessageSquare as IconMessage,
  Clock as IconClock,
  Folder as IconFolder,
  FolderPlus as IconFolderPlus,
  ChevronDown as IconChevronDown,
  ChevronRight as IconChevronRight,
  PanelLeft as IconLayoutSidebarLeftCollapse,
  PanelLeft as IconLayoutSidebar,
  Settings as IconSettings,
  Trash as IconTrash,
  Download as IconDownload,
  Pencil as IconEdit,
  X as IconX,
  Menu as IconMenu2,
  Image as IconPhoto,
  Check as IconCheck,
  Home as IconHome,
  MoreVertical as IconDotsVertical,
} from "lucide-react";
