// Centralized icon barrel - all icons must be imported from here
// This file re-exports everything from lucide-react to ensure consistent imports
export * from "lucide-react";

// Tabler icon mappings (for backward compatibility during migration)
// These are re-exported as Lucide equivalents
export {
  TrendingUp as IconTrendingUp,
  Scale as IconScale,
  Lightbulb as IconBulb,
  BookOpen as IconBook2,
  Shield as IconShield,
  Plane as IconPlane,
  Activity as IconActivity,
  Compass as IconCompass,
  Search as IconSearch,
  Plus as IconPlus,
  MessageSquare as IconMessage,
  Clock as IconClock,
  Folder as IconFolder,
  FolderPlus as IconFolderPlus,
  ChevronDown as IconChevronDown,
  ChevronRight as IconChevronRight,
  PanelLeft as IconLayoutSidebarLeftCollapse,
  PanelLeft as IconLayoutSidebar,
  Settings as IconSettings,
  Trash as IconTrash,
  Download as IconDownload,
  Pencil as IconEdit,
  X as IconX,
  Menu as IconMenu2,
  Image as IconPhoto,
  Check as IconCheck,
  Home as IconHome,
  MoreVertical as IconDotsVertical,
  Brain as IconBrain,
  ExternalLink as IconExternalLink,
  ArrowRight as IconArrowRight,
  Loader2 as IconLoader2,
  Bell as IconBell,
  ShieldCheck as IconShieldCheck,
  GraduationCap as IconSchool,
  TestTube as IconTestPipe,
  Files as IconFileStack,
  FileText as IconFileDescription,
  FileSearch as IconFileSearch,
  LayoutGrid as IconChartTreemap,
  FlaskConical as IconFlask,
  Globe as IconWorld,
} from "lucide-react";
