/**
 * HELIOS Safety Service
 *
 * Critical safety layer for medical triage system.
 * This service MUST run before any AI processing.
 *
 * Features:
 * 1. Emergency Pattern Detection (hard-coded, no AI dependency)
 * 2. Disclaimer Management
 * 3. Confidence Gating
 * 4. Hallucination Filtering
 * 5. Human Escalation Triggers
 * 6. Audit Logging
 */

import { supabase } from '@/integrations/supabase/client';

// ============================================================================
// Types
// ============================================================================

export interface EmergencyDetectionResult {
  isEmergency: boolean;
  patterns: string[];
  instructions: string;
  severity: 'critical' | 'high' | 'moderate' | null;
  emergencyNumber: string;
}

export interface DisclaimerConfig {
  type: 'consent' | 'post_assessment' | 'soap_footer' | 'pdf_watermark';
  text: string;
  required: boolean;
  dismissible: boolean;
}

export interface ConfidenceGateResult {
  allowed: boolean;
  confidence: number;
  action: 'proceed' | 'add_warning' | 'refuse_specific';
  message: string;
  requiresDoctorRecommendation: boolean;
}

export interface HallucinationFilterResult {
  isValid: boolean;
  validatedDiagnoses: ValidatedDiagnosis[];
  filteredDiagnoses: FilteredDiagnosis[];
  requiresReview: boolean;
}

export interface ValidatedDiagnosis {
  name: string;
  icd10Code: string;
  confidence: number;
  similarityScore: number;
}

export interface FilteredDiagnosis {
  name: string;
  providedIcd10: string | null;
  reason: 'invalid_icd10' | 'low_similarity' | 'not_found';
  similarityScore?: number;
}

export interface EscalationTrigger {
  triggered: boolean;
  reasons: EscalationReason[];
  urgency: 'immediate' | 'urgent' | 'standard';
  recommendedAction: string;
}

export interface EscalationReason {
  type: string;
  description: string;
  severity: 'critical' | 'high' | 'moderate';
}

export interface AuditLogEntry {
  timestamp: string;
  sessionId: string;
  eventType: AuditEventType;
  inputSummary: string;
  outputSummary: string;
  confidenceScores?: Record<string, number>;
  escalationTriggers?: string[];
  metadata?: Record<string, unknown>;
}

// Maps to helios.audit_event_type enum in database
export type AuditEventType =
  | 'session_started'
  | 'session_start'
  | 'phase_transition'
  | 'message_received'
  | 'message_sent'
  | 'agent_output'
  | 'tool_call'
  | 'tool_response'
  | 'red_flag_detected'
  | 'escalation_triggered'
  | 'safety_check'
  | 'booking_created'
  | 'handoff_generated'
  | 'session_completed'
  | 'voice_processed'
  | 'emotion_detected'
  | 'error_occurred'
  | 'confidence_gated'
  | 'diagnosis_filtered'
  | 'emergency_detected'
  | 'human_escalation';

// Safety-specific event type mapping
const SAFETY_EVENT_MAP = {
  session_start: 'session_started',
  emergency_detected: 'red_flag_detected',
  assessment_generated: 'agent_output',
  diagnosis_filtered: 'safety_check',
  confidence_gated: 'safety_check',
  human_escalation: 'escalation_triggered',
  consent_given: 'phase_transition',
  booking_initiated: 'booking_created',
  session_end: 'session_completed',
} as const;

// ============================================================================
// Required Disclaimers (DO NOT MODIFY TEXT)
// ============================================================================

export const CONSENT_DISCLAIMER = `
⚠️ IMPORTANT NOTICE

This AI-powered symptom assessment tool provides general health information only. By continuing, you acknowledge:

• This is NOT a substitute for professional medical advice, diagnosis, or treatment
• You should ALWAYS consult a qualified healthcare provider for personalized medical guidance
• This tool does NOT establish a doctor-patient relationship
• If you have a medical emergency, call 911 (or your local emergency number) immediately

Do you understand and wish to continue?
`;

export const POST_ASSESSMENT_DISCLAIMER = `
Remember: This assessment is not a diagnosis. Many conditions share similar symptoms. Please consult a healthcare professional for proper evaluation and treatment.
`;

export const SOAP_FOOTER_DISCLAIMER = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISCLAIMER: This SOAP note was generated by an AI-powered symptom assessment tool (HELIOS) and is provided for informational purposes only. It is NOT a medical diagnosis and should NOT be used as a substitute for professional medical advice, diagnosis, or treatment. Healthcare providers should independently verify all information and conduct their own clinical assessment. The AI-generated content may contain errors and should be reviewed critically.

This document does not establish a doctor-patient relationship.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

export const PDF_WATERMARK_TEXT = 'AI-GENERATED - NOT A MEDICAL DIAGNOSIS - FOR INFORMATIONAL PURPOSES ONLY';

export const EMERGENCY_INSTRUCTIONS = {
  general: 'If you are experiencing a medical emergency, please call 911 (or your local emergency number) immediately or go to the nearest emergency room.',
  heartAttack: 'Heart attack symptoms detected. Call 911 immediately. While waiting: sit or lie down, chew aspirin if available and not allergic, loosen tight clothing.',
  stroke: 'Possible stroke symptoms detected. Call 911 immediately. Note the time symptoms started. Do not drive yourself.',
  suicide: 'If you are having thoughts of suicide, please call 988 (Suicide & Crisis Lifeline) or 911 immediately. You are not alone and help is available.',
  overdose: 'Possible overdose detected. Call 911 immediately. If Narcan (naloxone) is available, administer it. Stay with the person.',
  severeBreathing: 'Severe breathing difficulty detected. Call 911 immediately. Sit upright if possible. Do not lie flat.',
  severebleeding: 'Severe bleeding detected. Call 911 immediately. Apply direct pressure to the wound with a clean cloth. Do not remove the cloth.',
  anaphylaxis: 'Possible severe allergic reaction. Call 911 immediately. Use epinephrine auto-injector (EpiPen) if available.',
};

// ============================================================================
// 1. Emergency Pattern Detector
// ============================================================================

/**
 * HARD-CODED emergency patterns - NO AI DEPENDENCY
 * These patterns MUST run before any AI processing
 */
const EMERGENCY_PATTERNS = {
  // Heart Attack / Cardiac Emergency
  heartAttack: {
    patterns: [
      /\b(heart\s*attack|cardiac\s*arrest|chest\s*pain.*crushing|crushing.*chest)/i,
      /\b(chest\s*pain.*radiat|radiat.*arm|radiat.*jaw)/i,
      /\b(can'?t\s*breathe.*chest|chest.*can'?t\s*breathe)/i,
      /\b(severe\s*chest\s*pain|elephant.*chest)/i,
      /\b(diaphoresis|sweating\s*profusely).*chest/i,
      /\bpulseless\b/i,
      /\bno\s*pulse\b/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.heartAttack,
  },

  // Stroke
  stroke: {
    patterns: [
      /\b(stroke|cva|cerebrovascular)/i,
      /\b(face\s*droop|facial\s*droop|one\s*side.*face)/i,
      /\b(arm\s*weak|can'?t\s*(lift|move|raise)\s*(my\s*)?(arm|hand))/i,
      /\b(slurred\s*speech|can'?t\s*speak|speech\s*difficult)/i,
      /\b(sudden.*numb|numb.*sudden|sudden.*weak|weak.*sudden)/i,
      /\b(worst\s*headache|thunderclap)/i,
      /\bfast\s*positive\b/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.stroke,
  },

  // Suicide / Self-Harm
  suicide: {
    patterns: [
      /\b(suicid|kill\s*(my)?self|end\s*(my\s*)?life)/i,
      /\b(want\s*to\s*die|wanna\s*die|don'?t\s*want\s*to\s*live)/i,
      /\b(cut\s*(my)?self|cutting\s*(my)?self|self[\s-]?harm)/i,
      /\b(overdose\s*on\s*purpose|take\s*all\s*(my\s*)?pills)/i,
      /\b(plan\s*to\s*(kill|hurt|harm)\s*(my)?self)/i,
      /\b(no\s*reason\s*to\s*live|better\s*off\s*dead)/i,
      /\b(bought\s*a\s*gun|have\s*a\s*gun).*harm/i,
      /\bhomicid/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.suicide,
  },

  // Overdose / Poisoning
  overdose: {
    patterns: [
      /\b(overdos|od'?d|od'?ing)/i,
      /\b(took\s*too\s*(many|much)|swallowed.*pills)/i,
      /\b(poison|toxic|ingested.*chemical)/i,
      /\b(heroin|fentanyl|opioid).*unresponsive/i,
      /\b(blue\s*lips|not\s*responding|barely\s*breathing)/i,
      /\b(drank.*bleach|drank.*antifreeze)/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.overdose,
  },

  // Severe Breathing Difficulty
  severeBreathing: {
    patterns: [
      /\b(can'?t\s*breathe|cannot\s*breathe|unable\s*to\s*breathe)/i,
      /\b(struggling\s*to\s*breathe|gasping|choking)/i,
      /\b(lips\s*(turning\s*)?blue|cyanosis|turning\s*blue)/i,
      /\b(severe\s*(shortness\s*of\s*breath|dyspnea|respiratory\s*distress))/i,
      /\b(airway\s*obstruct|throat\s*swelling|can'?t\s*swallow)/i,
      /\b(anaphyla|severe\s*allergic)/i,
      /\b(stridor|wheezing\s*severe)/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.severeBreathing,
  },

  // Severe Bleeding
  severebleeding: {
    patterns: [
      /\b(severe\s*bleed|massive\s*bleed|won'?t\s*stop\s*bleed)/i,
      /\b(blood\s*(everywhere|gushing|spurting|pouring))/i,
      /\b(arterial\s*bleed|pulsatile\s*bleed)/i,
      /\b(vomiting\s*blood|coughing.*blood.*lot)/i,
      /\b(blood\s*in\s*stool.*massive|massive.*rectal\s*bleed)/i,
      /\b(trauma.*bleeding|accident.*bleeding)/i,
      /\b(amputat|severed)/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.severebleeding,
  },

  // Anaphylaxis
  anaphylaxis: {
    patterns: [
      /\b(anaphyla|anaphylactic)/i,
      /\b(throat.*swell|swell.*throat|tongue.*swell)/i,
      /\b(epipen|epinephrine)/i,
      /\b(allergic\s*reaction.*severe|severe.*allergic)/i,
      /\b(hives.*breathing|breathing.*hives)/i,
      /\b(bee\s*sting.*can'?t\s*breathe|peanut.*can'?t\s*breathe)/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.anaphylaxis,
  },

  // Loss of Consciousness
  unconscious: {
    patterns: [
      /\b(unconscious|unresponsive|passed\s*out)/i,
      /\b(won'?t\s*wake\s*up|can'?t\s*wake)/i,
      /\b(collapsed|found\s*(him|her|them)\s*on\s*(the\s*)?(floor|ground))/i,
      /\b(not\s*moving|not\s*responding)/i,
      /\b(seizure.*not\s*stopping|status\s*epilepticus)/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.general,
  },

  // Pregnancy Emergencies
  pregnancyEmergency: {
    patterns: [
      /\b(pregnant.*bleed|bleed.*pregnant).*heavy/i,
      /\b(water\s*broke.*preterm|preterm.*labor)/i,
      /\b(eclampsia|seizure.*pregnant)/i,
      /\b(placent.*abrupt|cord\s*prolaps)/i,
      /\b(baby\s*(not\s*)?moving.*pregnant)/i,
    ],
    severity: 'critical' as const,
    instructions: EMERGENCY_INSTRUCTIONS.general,
  },
};

/**
 * Detect emergency patterns in user input
 * MUST run before any AI processing
 *
 * @param input - User's message text
 * @param language - User's language for localized emergency number
 * @returns Emergency detection result
 */
export function detectEmergency(
  input: string,
  language: 'en' | 'es' | 'fr' = 'en'
): EmergencyDetectionResult {
  const matchedPatterns: string[] = [];
  let highestSeverity: 'critical' | 'high' | 'moderate' | null = null;
  let instructions = EMERGENCY_INSTRUCTIONS.general;

  const normalizedInput = input.toLowerCase();

  // Check all emergency pattern categories
  for (const [category, config] of Object.entries(EMERGENCY_PATTERNS)) {
    for (const pattern of config.patterns) {
      if (pattern.test(normalizedInput)) {
        matchedPatterns.push(category);
        highestSeverity = config.severity;
        instructions = config.instructions;
        break; // Only need one match per category
      }
    }
  }

  // Remove duplicates
  const uniquePatterns = [...new Set(matchedPatterns)];

  // Get localized emergency number
  const emergencyNumbers: Record<string, string> = {
    en: '911',
    es: '911',
    fr: '15 (SAMU) or 112',
  };

  return {
    isEmergency: uniquePatterns.length > 0,
    patterns: uniquePatterns,
    instructions: uniquePatterns.length > 0 ? instructions : '',
    severity: highestSeverity,
    emergencyNumber: emergencyNumbers[language] || '911',
  };
}

// ============================================================================
// 2. Disclaimer Manager
// ============================================================================

/**
 * Get all disclaimers configuration
 */
export function getDisclaimers(): Record<string, DisclaimerConfig> {
  return {
    consent: {
      type: 'consent',
      text: CONSENT_DISCLAIMER,
      required: true,
      dismissible: false,
    },
    postAssessment: {
      type: 'post_assessment',
      text: POST_ASSESSMENT_DISCLAIMER,
      required: true,
      dismissible: false,
    },
    soapFooter: {
      type: 'soap_footer',
      text: SOAP_FOOTER_DISCLAIMER,
      required: true,
      dismissible: false,
    },
    pdfWatermark: {
      type: 'pdf_watermark',
      text: PDF_WATERMARK_TEXT,
      required: true,
      dismissible: false,
    },
  };
}

/**
 * Get localized disclaimer text
 */
export function getLocalizedDisclaimer(
  type: 'consent' | 'post_assessment' | 'soap_footer' | 'pdf_watermark',
  language: 'en' | 'es' | 'fr' = 'en'
): string {
  const disclaimers = {
    consent: {
      en: CONSENT_DISCLAIMER,
      es: `
⚠️ AVISO IMPORTANTE

Esta herramienta de evaluación de síntomas impulsada por IA proporciona solo información general de salud. Al continuar, usted reconoce:

• Esto NO sustituye el consejo, diagnóstico o tratamiento médico profesional
• SIEMPRE debe consultar a un proveedor de atención médica calificado para orientación médica personalizada
• Esta herramienta NO establece una relación médico-paciente
• Si tiene una emergencia médica, llame al 911 (o su número de emergencia local) inmediatamente

¿Entiende y desea continuar?
`,
      fr: `
⚠️ AVIS IMPORTANT

Cet outil d'évaluation des symptômes alimenté par l'IA fournit uniquement des informations générales sur la santé. En continuant, vous reconnaissez :

• Ceci N'EST PAS un substitut aux conseils, diagnostics ou traitements médicaux professionnels
• Vous devriez TOUJOURS consulter un professionnel de santé qualifié pour des conseils médicaux personnalisés
• Cet outil N'établit PAS de relation médecin-patient
• En cas d'urgence médicale, appelez le 15 (SAMU) ou le 112 immédiatement

Comprenez-vous et souhaitez-vous continuer ?
`,
    },
    post_assessment: {
      en: POST_ASSESSMENT_DISCLAIMER,
      es: 'Recuerde: Esta evaluación no es un diagnóstico. Muchas condiciones comparten síntomas similares. Por favor consulte a un profesional de la salud para una evaluación y tratamiento adecuados.',
      fr: 'Rappel : Cette évaluation n\'est pas un diagnostic. De nombreuses conditions partagent des symptômes similaires. Veuillez consulter un professionnel de santé pour une évaluation et un traitement appropriés.',
    },
    soap_footer: {
      en: SOAP_FOOTER_DISCLAIMER,
      es: `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DESCARGO DE RESPONSABILIDAD: Esta nota SOAP fue generada por una herramienta de evaluación de síntomas impulsada por IA (HELIOS) y se proporciona solo con fines informativos. NO es un diagnóstico médico y NO debe usarse como sustituto del consejo, diagnóstico o tratamiento médico profesional. Los proveedores de atención médica deben verificar independientemente toda la información y realizar su propia evaluación clínica. El contenido generado por IA puede contener errores y debe revisarse críticamente.

Este documento no establece una relación médico-paciente.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`,
      fr: `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

AVERTISSEMENT : Cette note SOAP a été générée par un outil d'évaluation des symptômes alimenté par l'IA (HELIOS) et est fournie à titre informatif uniquement. Ce n'est PAS un diagnostic médical et ne doit PAS être utilisé comme substitut aux conseils, diagnostics ou traitements médicaux professionnels. Les professionnels de santé doivent vérifier indépendamment toutes les informations et effectuer leur propre évaluation clinique. Le contenu généré par l'IA peut contenir des erreurs et doit être examiné de manière critique.

Ce document n'établit pas de relation médecin-patient.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`,
    },
    pdf_watermark: {
      en: PDF_WATERMARK_TEXT,
      es: 'GENERADO POR IA - NO ES UN DIAGNÓSTICO MÉDICO - SOLO CON FINES INFORMATIVOS',
      fr: 'GÉNÉRÉ PAR IA - PAS UN DIAGNOSTIC MÉDICAL - À TITRE INFORMATIF UNIQUEMENT',
    },
  };

  return disclaimers[type][language] || disclaimers[type].en;
}

/**
 * Validate that consent was given before proceeding
 */
export function validateConsent(consentGiven: boolean): boolean {
  if (!consentGiven) {
    console.warn('[SAFETY] Attempted to proceed without consent');
  }
  return consentGiven;
}

// ============================================================================
// 3. Confidence Gating
// ============================================================================

const CONFIDENCE_THRESHOLDS = {
  REFUSE_SPECIFIC: 0.60,
  ADD_WARNING: 0.85,
  PROCEED_FREELY: 1.0,
};

/**
 * Gate responses based on confidence level
 *
 * @param confidence - Consensus confidence score (0-1)
 * @returns Gating result with action to take
 */
export function gateByConfidence(confidence: number): ConfidenceGateResult {
  // Normalize confidence to 0-1 if percentage provided
  const normalizedConfidence = confidence > 1 ? confidence / 100 : confidence;

  if (normalizedConfidence < CONFIDENCE_THRESHOLDS.REFUSE_SPECIFIC) {
    // Below 60%: Refuse specific diagnosis
    return {
      allowed: false,
      confidence: normalizedConfidence,
      action: 'refuse_specific',
      message:
        'Due to the complexity of your symptoms, we cannot provide a specific assessment. ' +
        'We strongly recommend consulting with a healthcare professional for proper evaluation.',
      requiresDoctorRecommendation: true,
    };
  } else if (normalizedConfidence < CONFIDENCE_THRESHOLDS.ADD_WARNING) {
    // 60-85%: Add prominent warning
    return {
      allowed: true,
      confidence: normalizedConfidence,
      action: 'add_warning',
      message:
        'This assessment has moderate confidence. ' +
        'We recommend consulting with a healthcare professional to confirm these findings.',
      requiresDoctorRecommendation: true,
    };
  } else {
    // Above 85%: Proceed with standard disclaimer
    return {
      allowed: true,
      confidence: normalizedConfidence,
      action: 'proceed',
      message: POST_ASSESSMENT_DISCLAIMER,
      requiresDoctorRecommendation: false,
    };
  }
}

/**
 * Log low-confidence responses for review
 */
export async function logLowConfidenceResponse(
  sessionId: string,
  confidence: number,
  diagnoses: string[],
  action: string
): Promise<void> {
  if (confidence < CONFIDENCE_THRESHOLDS.ADD_WARNING) {
    console.warn(
      `[SAFETY] Low confidence response: session=${sessionId}, confidence=${confidence}, action=${action}`
    );

    await logAuditEvent({
      sessionId,
      eventType: 'confidence_gated',
      inputSummary: `Diagnoses considered: ${diagnoses.join(', ')}`,
      outputSummary: `Action: ${action}`,
      confidenceScores: { overall: confidence },
    });
  }
}

// ============================================================================
// 4. Hallucination Filter
// ============================================================================

const ICD10_CODE_PATTERN = /^[A-TV-Z][0-9][0-9AB]\.?[0-9A-TV-Z]{0,4}$/;
const SIMILARITY_THRESHOLD = 0.3;

/**
 * Validate that a diagnosis has a valid ICD-10 code
 */
export function isValidICD10Code(code: string): boolean {
  if (!code || typeof code !== 'string') return false;
  return ICD10_CODE_PATTERN.test(code.trim().toUpperCase());
}

/**
 * Filter diagnoses for hallucinations
 *
 * @param diagnoses - Array of diagnoses with ICD-10 codes and similarity scores
 * @returns Filter result with validated and rejected diagnoses
 */
export function filterHallucinations(
  diagnoses: Array<{
    name: string;
    icd10Code: string | null;
    confidence: number;
    nlmSimilarityScore?: number;
  }>
): HallucinationFilterResult {
  const validatedDiagnoses: ValidatedDiagnosis[] = [];
  const filteredDiagnoses: FilteredDiagnosis[] = [];
  let requiresReview = false;

  for (const diagnosis of diagnoses) {
    const { name, icd10Code, confidence, nlmSimilarityScore } = diagnosis;

    // Check 1: Valid ICD-10 code format
    if (!icd10Code || !isValidICD10Code(icd10Code)) {
      filteredDiagnoses.push({
        name,
        providedIcd10: icd10Code,
        reason: 'invalid_icd10',
      });
      requiresReview = true;
      continue;
    }

    // Check 2: Similarity score threshold
    const similarityScore = nlmSimilarityScore ?? 1.0;
    if (similarityScore < SIMILARITY_THRESHOLD) {
      filteredDiagnoses.push({
        name,
        providedIcd10: icd10Code,
        reason: 'low_similarity',
        similarityScore,
      });
      requiresReview = true;
      continue;
    }

    // Diagnosis passed all checks
    validatedDiagnoses.push({
      name,
      icd10Code,
      confidence,
      similarityScore,
    });
  }

  // Log filtered diagnoses for review
  if (filteredDiagnoses.length > 0) {
    console.warn(
      `[SAFETY] Hallucination filter removed ${filteredDiagnoses.length} diagnoses:`,
      filteredDiagnoses.map((d) => `${d.name} (${d.reason})`).join(', ')
    );
  }

  return {
    isValid: filteredDiagnoses.length === 0,
    validatedDiagnoses,
    filteredDiagnoses,
    requiresReview,
  };
}

/**
 * Log filtered diagnoses for manual review
 */
export async function logFilteredDiagnoses(
  sessionId: string,
  filteredDiagnoses: FilteredDiagnosis[]
): Promise<void> {
  if (filteredDiagnoses.length === 0) return;

  await logAuditEvent({
    sessionId,
    eventType: 'diagnosis_filtered',
    inputSummary: 'Diagnoses submitted for validation',
    outputSummary: `Filtered: ${filteredDiagnoses.map((d) => `${d.name} (${d.reason})`).join(', ')}`,
    metadata: { filteredDiagnoses },
  });
}

// ============================================================================
// 5. Human Escalation Triggers
// ============================================================================

const ESCALATION_SYMPTOMS_PEDIATRIC = [
  'fever',
  'seizure',
  'difficulty breathing',
  'not responding',
  'rash',
  'vomiting blood',
  'severe abdominal pain',
  'head injury',
  'ingestion',
  'poisoning',
];

const PREGNANCY_CONCERNS = [
  'bleeding',
  'cramping',
  'contractions',
  'decreased fetal movement',
  'no fetal movement',
  'severe headache',
  'blurred vision',
  'swelling',
  'high blood pressure',
  'preeclampsia',
];

/**
 * Check if human escalation is needed
 */
export function checkEscalationTriggers(params: {
  kendallW: number;
  maxRoundsReached: boolean;
  agentLifeThreatFlags: boolean[];
  patientAge?: number;
  symptoms: string[];
  isPregnant?: boolean;
}): EscalationTrigger {
  const reasons: EscalationReason[] = [];
  const {
    kendallW,
    maxRoundsReached,
    agentLifeThreatFlags,
    patientAge,
    symptoms,
    isPregnant,
  } = params;

  const normalizedSymptoms = symptoms.map((s) => s.toLowerCase());

  // Trigger 1: Low consensus after max rounds
  if (kendallW < 0.7 && maxRoundsReached) {
    reasons.push({
      type: 'low_consensus',
      description: `Kendall's W coefficient (${kendallW.toFixed(2)}) below threshold after maximum debate rounds`,
      severity: 'high',
    });
  }

  // Trigger 2: Any agent flags life-threatening concern
  const lifeThreatCount = agentLifeThreatFlags.filter(Boolean).length;
  if (lifeThreatCount > 0) {
    reasons.push({
      type: 'life_threat_flag',
      description: `${lifeThreatCount} specialist(s) flagged potential life-threatening condition`,
      severity: 'critical',
    });
  }

  // Trigger 3: Pediatric patient with concerning symptoms
  if (patientAge !== undefined && patientAge < 18) {
    const matchingSymptoms = normalizedSymptoms.filter((s) =>
      ESCALATION_SYMPTOMS_PEDIATRIC.some((es) => s.includes(es))
    );

    if (matchingSymptoms.length > 0) {
      reasons.push({
        type: 'pediatric_concern',
        description: `Pediatric patient (age ${patientAge}) with symptoms: ${matchingSymptoms.join(', ')}`,
        severity: patientAge < 2 ? 'critical' : 'high',
      });
    }

    // Special case: infants under 3 months with fever
    if (patientAge < 0.25 && normalizedSymptoms.some((s) => s.includes('fever'))) {
      reasons.push({
        type: 'infant_fever',
        description: 'Infant under 3 months with fever - requires immediate evaluation',
        severity: 'critical',
      });
    }
  }

  // Trigger 4: Pregnancy-related concerns
  if (isPregnant) {
    const matchingConcerns = normalizedSymptoms.filter((s) =>
      PREGNANCY_CONCERNS.some((pc) => s.includes(pc))
    );

    if (matchingConcerns.length > 0) {
      reasons.push({
        type: 'pregnancy_concern',
        description: `Pregnancy-related symptoms: ${matchingConcerns.join(', ')}`,
        severity: 'high',
      });
    }
  }

  // Determine urgency
  let urgency: 'immediate' | 'urgent' | 'standard' = 'standard';
  if (reasons.some((r) => r.severity === 'critical')) {
    urgency = 'immediate';
  } else if (reasons.some((r) => r.severity === 'high')) {
    urgency = 'urgent';
  }

  // Generate recommended action
  let recommendedAction = 'Continue with AI-assisted assessment';
  if (urgency === 'immediate') {
    recommendedAction =
      'Immediate human physician review required. Consider emergency referral.';
  } else if (urgency === 'urgent') {
    recommendedAction =
      'Expedited human physician review recommended before providing assessment.';
  }

  return {
    triggered: reasons.length > 0,
    reasons,
    urgency,
    recommendedAction,
  };
}

// ============================================================================
// 6. Audit Logger
// ============================================================================

/**
 * Redact PHI from text
 */
function redactPHI(text: string): string {
  // Redact patterns that might contain PHI
  return text
    // Names (simple pattern - in production use NER)
    .replace(/\b(Mr\.|Mrs\.|Ms\.|Dr\.)\s+[A-Z][a-z]+/g, '[NAME]')
    // Phone numbers
    .replace(/\b\d{3}[-.]?\d{3}[-.]?\d{4}\b/g, '[PHONE]')
    // Email addresses
    .replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, '[EMAIL]')
    // SSN
    .replace(/\b\d{3}-\d{2}-\d{4}\b/g, '[SSN]')
    // Dates of birth (various formats)
    .replace(
      /\b(0?[1-9]|1[0-2])[\/\-](0?[1-9]|[12]\d|3[01])[\/\-](19|20)\d{2}\b/g,
      '[DOB]'
    )
    // Medical record numbers (simple pattern)
    .replace(/\b(MRN|MR#?|Medical Record)[:\s]*\d+/gi, '[MRN]')
    // Addresses (simple pattern)
    .replace(/\b\d+\s+[A-Za-z]+\s+(Street|St|Avenue|Ave|Road|Rd|Drive|Dr|Lane|Ln|Boulevard|Blvd)\b/gi, '[ADDRESS]');
}

/**
 * Generate a simple hash for audit log integrity
 * In production, use a cryptographic hash function
 */
function generateEventHash(payload: object, previousHash: string): string {
  const content = JSON.stringify(payload) + previousHash;
  // Simple hash for demo - in production use crypto.subtle.digest
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  return `hash_${Math.abs(hash).toString(16)}`;
}

// Track previous hash for chain integrity
let lastEventHash = 'genesis';

/**
 * Log an audit event to helios.audit_log table
 * Uses WORM (Write Once Read Many) pattern with hash chain
 */
export async function logAuditEvent(
  entry: Omit<AuditLogEntry, 'timestamp'>,
  language: 'en' | 'es' | 'fr' = 'en'
): Promise<void> {
  const timestamp = new Date().toISOString();

  // Build the event payload with redacted PHI
  const eventPayload = {
    input_summary: redactPHI(entry.inputSummary),
    output_summary: redactPHI(entry.outputSummary),
    confidence_scores: entry.confidenceScores,
    escalation_triggers: entry.escalationTriggers,
    metadata: entry.metadata,
    safety_event_type: entry.eventType, // Original safety event type
  };

  // Generate hash for integrity chain
  const eventHash = generateEventHash(eventPayload, lastEventHash);

  // Map safety event type to HELIOS audit event type
  const mappedEventType = SAFETY_EVENT_MAP[entry.eventType as keyof typeof SAFETY_EVENT_MAP] || 'safety_check';

  // Log to console in development
  console.log('[AUDIT]', JSON.stringify({
    timestamp,
    sessionId: entry.sessionId,
    eventType: mappedEventType,
    ...eventPayload,
  }, null, 2));

  // Store in helios.audit_log table - disabled until table is created
  // For now, just log to console
  console.log('[AUDIT] Entry logged (DB disabled):', {
    session_id: entry.sessionId,
    event_type: mappedEventType,
    timestamp,
  });
}

/**
 * Log session start
 */
export async function logSessionStart(
  sessionId: string,
  language: 'en' | 'es' | 'fr' = 'en'
): Promise<void> {
  await logAuditEvent({
    sessionId,
    eventType: 'session_start',
    inputSummary: `Language: ${language}`,
    outputSummary: 'Session initialized',
  }, language);
}

/**
 * Log emergency detection
 */
export async function logEmergencyDetected(
  sessionId: string,
  detection: EmergencyDetectionResult
): Promise<void> {
  await logAuditEvent({
    sessionId,
    eventType: 'emergency_detected',
    inputSummary: `Patterns: ${detection.patterns.join(', ')}`,
    outputSummary: `Severity: ${detection.severity}, Instructions provided`,
    escalationTriggers: detection.patterns,
    metadata: {
      severity: detection.severity,
      emergencyNumber: detection.emergencyNumber,
    },
  });
}

/**
 * Log human escalation
 */
export async function logHumanEscalation(
  sessionId: string,
  trigger: EscalationTrigger
): Promise<void> {
  await logAuditEvent({
    sessionId,
    eventType: 'human_escalation',
    inputSummary: `Reasons: ${trigger.reasons.map((r) => r.type).join(', ')}`,
    outputSummary: `Urgency: ${trigger.urgency}, Action: ${trigger.recommendedAction}`,
    escalationTriggers: trigger.reasons.map((r) => r.type),
    metadata: {
      urgency: trigger.urgency,
      reasons: trigger.reasons,
    },
  });
}

// ============================================================================
// Main Safety Check Pipeline
// ============================================================================

export interface SafetyCheckResult {
  passed: boolean;
  emergencyDetected: boolean;
  emergencyResult?: EmergencyDetectionResult;
  requiresHumanEscalation: boolean;
  escalationResult?: EscalationTrigger;
  confidenceGateResult?: ConfidenceGateResult;
  hallucinationFilterResult?: HallucinationFilterResult;
  warnings: string[];
}

/**
 * Run complete safety check pipeline
 * This should be called before presenting any AI-generated assessment
 */
export async function runSafetyChecks(params: {
  sessionId: string;
  userInput: string;
  diagnoses?: Array<{
    name: string;
    icd10Code: string | null;
    confidence: number;
    nlmSimilarityScore?: number;
  }>;
  consensusConfidence?: number;
  kendallW?: number;
  maxRoundsReached?: boolean;
  agentLifeThreatFlags?: boolean[];
  patientAge?: number;
  symptoms?: string[];
  isPregnant?: boolean;
  language?: 'en' | 'es' | 'fr';
}): Promise<SafetyCheckResult> {
  const warnings: string[] = [];
  const result: SafetyCheckResult = {
    passed: true,
    emergencyDetected: false,
    requiresHumanEscalation: false,
    warnings,
  };

  // 1. Emergency Detection (MUST run first)
  const emergencyResult = detectEmergency(
    params.userInput,
    params.language || 'en'
  );
  if (emergencyResult.isEmergency) {
    result.emergencyDetected = true;
    result.emergencyResult = emergencyResult;
    result.passed = false;
    warnings.push(`EMERGENCY DETECTED: ${emergencyResult.patterns.join(', ')}`);

    await logEmergencyDetected(params.sessionId, emergencyResult);

    // Return immediately for emergencies
    return result;
  }

  // 2. Human Escalation Check
  if (
    params.kendallW !== undefined &&
    params.maxRoundsReached !== undefined &&
    params.agentLifeThreatFlags !== undefined
  ) {
    const escalationResult = checkEscalationTriggers({
      kendallW: params.kendallW,
      maxRoundsReached: params.maxRoundsReached,
      agentLifeThreatFlags: params.agentLifeThreatFlags,
      patientAge: params.patientAge,
      symptoms: params.symptoms || [],
      isPregnant: params.isPregnant,
    });

    if (escalationResult.triggered) {
      result.requiresHumanEscalation = true;
      result.escalationResult = escalationResult;
      warnings.push(
        `ESCALATION: ${escalationResult.reasons.map((r) => r.description).join('; ')}`
      );

      await logHumanEscalation(params.sessionId, escalationResult);
    }
  }

  // 3. Confidence Gating
  if (params.consensusConfidence !== undefined) {
    const confidenceResult = gateByConfidence(params.consensusConfidence);
    result.confidenceGateResult = confidenceResult;

    if (!confidenceResult.allowed) {
      result.passed = false;
      warnings.push(`CONFIDENCE GATE: ${confidenceResult.message}`);
    } else if (confidenceResult.action === 'add_warning') {
      warnings.push(`CONFIDENCE WARNING: ${confidenceResult.message}`);
    }
  }

  // 4. Hallucination Filtering
  if (params.diagnoses && params.diagnoses.length > 0) {
    const hallucinationResult = filterHallucinations(params.diagnoses);
    result.hallucinationFilterResult = hallucinationResult;

    if (hallucinationResult.filteredDiagnoses.length > 0) {
      warnings.push(
        `HALLUCINATION FILTER: Removed ${hallucinationResult.filteredDiagnoses.length} invalid diagnoses`
      );

      await logFilteredDiagnoses(
        params.sessionId,
        hallucinationResult.filteredDiagnoses
      );
    }
  }

  return result;
}

// ============================================================================
// Export All
// ============================================================================

export default {
  // Emergency Detection
  detectEmergency,
  EMERGENCY_PATTERNS,
  EMERGENCY_INSTRUCTIONS,

  // Disclaimers
  CONSENT_DISCLAIMER,
  POST_ASSESSMENT_DISCLAIMER,
  SOAP_FOOTER_DISCLAIMER,
  PDF_WATERMARK_TEXT,
  getDisclaimers,
  getLocalizedDisclaimer,
  validateConsent,

  // Confidence Gating
  gateByConfidence,
  logLowConfidenceResponse,
  CONFIDENCE_THRESHOLDS,

  // Hallucination Filter
  isValidICD10Code,
  filterHallucinations,
  logFilteredDiagnoses,

  // Human Escalation
  checkEscalationTriggers,

  // Audit Logging
  logAuditEvent,
  logSessionStart,
  logEmergencyDetected,
  logHumanEscalation,

  // Main Pipeline
  runSafetyChecks,
};
