/**
 * HELIOS 107-Agent Taxonomy
 * Complete hierarchy of specialized clinical agents
 */

export type AgentTier = 'supervisor' | 'specialist' | 'worker';
export type AgentTeam =
  | 'orchestration'
  | 'intake'
  | 'history'
  | 'triage'
  | 'differential'
  | 'plan'
  | 'safety'
  | 'documentation'
  | 'booking'
  | 'knowledge';

export interface AgentDefinition {
  id: string;
  name: string;
  team: AgentTeam;
  tier: AgentTier;
  model: 'opus' | 'sonnet' | 'haiku';
  description: string;
  canConsult: string[];  // Agent IDs this agent can consult
  reportsTo?: string;    // Supervisor agent ID
  supervises?: string[]; // Subordinate agent IDs
}

/**
 * COMPLETE 107-AGENT REGISTRY
 * Organized by team with supervisor → specialist → worker hierarchy
 */
export const AGENT_REGISTRY: Record<string, AgentDefinition> = {
  // ============================================
  // ORCHESTRATION TEAM (5 agents)
  // ============================================
  'orch_master': {
    id: 'orch_master',
    name: 'Master Orchestrator',
    team: 'orchestration',
    tier: 'supervisor',
    model: 'opus',
    description: 'Overall session coordinator, routes to teams',
    canConsult: ['orch_router', 'orch_consensus', 'safety_chief'],
    supervises: ['orch_router', 'orch_consensus', 'orch_state', 'orch_quality'],
  },
  'orch_router': {
    id: 'orch_router',
    name: 'Phase Router',
    team: 'orchestration',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Determines which team/phase to activate next',
    canConsult: ['orch_master', 'orch_state'],
    reportsTo: 'orch_master',
  },
  'orch_consensus': {
    id: 'orch_consensus',
    name: 'Consensus Builder',
    team: 'orchestration',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Aggregates agent opinions, builds team consensus',
    canConsult: ['orch_master', 'diff_chief', 'triage_chief'],
    reportsTo: 'orch_master',
  },
  'orch_state': {
    id: 'orch_state',
    name: 'State Manager',
    team: 'orchestration',
    tier: 'worker',
    model: 'haiku',
    description: 'Maintains session state, tracks phase transitions',
    canConsult: ['orch_router'],
    reportsTo: 'orch_master',
  },
  'orch_quality': {
    id: 'orch_quality',
    name: 'Quality Monitor',
    team: 'orchestration',
    tier: 'worker',
    model: 'haiku',
    description: 'Monitors response quality, flags issues',
    canConsult: ['orch_master'],
    reportsTo: 'orch_master',
  },

  // ============================================
  // INTAKE TEAM (8 agents)
  // ============================================
  'intake_chief': {
    id: 'intake_chief',
    name: 'Intake Coordinator',
    team: 'intake',
    tier: 'supervisor',
    model: 'sonnet',
    description: 'Coordinates initial patient contact',
    canConsult: ['orch_master', 'safety_chief', 'history_chief'],
    supervises: ['intake_greeter', 'intake_demographics', 'intake_consent', 'intake_language', 'intake_urgency', 'intake_context', 'intake_validator'],
  },
  'intake_greeter': {
    id: 'intake_greeter',
    name: 'Patient Greeter',
    team: 'intake',
    tier: 'specialist',
    model: 'haiku',
    description: 'Welcomes patient, sets empathetic tone',
    canConsult: ['intake_chief', 'intake_language'],
    reportsTo: 'intake_chief',
  },
  'intake_demographics': {
    id: 'intake_demographics',
    name: 'Demographics Collector',
    team: 'intake',
    tier: 'worker',
    model: 'haiku',
    description: 'Collects age, sex, basic info',
    canConsult: ['intake_chief'],
    reportsTo: 'intake_chief',
  },
  'intake_consent': {
    id: 'intake_consent',
    name: 'Consent Manager',
    team: 'intake',
    tier: 'worker',
    model: 'haiku',
    description: 'Handles terms acceptance, privacy disclosures',
    canConsult: ['intake_chief'],
    reportsTo: 'intake_chief',
  },
  'intake_language': {
    id: 'intake_language',
    name: 'Language Detector',
    team: 'intake',
    tier: 'worker',
    model: 'haiku',
    description: 'Detects patient language preference',
    canConsult: ['intake_chief'],
    reportsTo: 'intake_chief',
  },
  'intake_urgency': {
    id: 'intake_urgency',
    name: 'Initial Urgency Screener',
    team: 'intake',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Quick screen for emergency keywords',
    canConsult: ['intake_chief', 'safety_chief'],
    reportsTo: 'intake_chief',
  },
  'intake_context': {
    id: 'intake_context',
    name: 'Context Gatherer',
    team: 'intake',
    tier: 'worker',
    model: 'haiku',
    description: 'Gathers visit context (time, location, etc)',
    canConsult: ['intake_chief'],
    reportsTo: 'intake_chief',
  },
  'intake_validator': {
    id: 'intake_validator',
    name: 'Input Validator',
    team: 'intake',
    tier: 'worker',
    model: 'haiku',
    description: 'Validates input completeness before handoff',
    canConsult: ['intake_chief'],
    reportsTo: 'intake_chief',
  },

  // ============================================
  // HISTORY TEAM (15 agents)
  // ============================================
  'history_chief': {
    id: 'history_chief',
    name: 'History Coordinator',
    team: 'history',
    tier: 'supervisor',
    model: 'sonnet',
    description: 'Coordinates comprehensive history gathering',
    canConsult: ['orch_master', 'intake_chief', 'triage_chief', 'safety_chief'],
    supervises: ['history_cc', 'history_hpi', 'history_pmh', 'history_meds', 'history_allergy', 'history_social', 'history_family', 'history_ros', 'history_surgical', 'history_psych', 'history_ob', 'history_peds', 'history_travel', 'history_occupational'],
  },
  'history_cc': {
    id: 'history_cc',
    name: 'Chief Complaint Extractor',
    team: 'history',
    tier: 'specialist',
    model: 'haiku',
    description: 'Extracts primary reason for visit',
    canConsult: ['history_chief', 'history_hpi'],
    reportsTo: 'history_chief',
  },
  'history_hpi': {
    id: 'history_hpi',
    name: 'HPI Gatherer',
    team: 'history',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Gathers History of Present Illness using OLDCARTS',
    canConsult: ['history_chief', 'history_cc', 'history_ros'],
    reportsTo: 'history_chief',
  },
  'history_pmh': {
    id: 'history_pmh',
    name: 'Past Medical History',
    team: 'history',
    tier: 'worker',
    model: 'haiku',
    description: 'Collects past medical conditions',
    canConsult: ['history_chief'],
    reportsTo: 'history_chief',
  },
  'history_meds': {
    id: 'history_meds',
    name: 'Medication Reviewer',
    team: 'history',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Reviews current medications, checks interactions',
    canConsult: ['history_chief', 'knowledge_drugs', 'safety_drug'],
    reportsTo: 'history_chief',
  },
  'history_allergy': {
    id: 'history_allergy',
    name: 'Allergy Checker',
    team: 'history',
    tier: 'worker',
    model: 'haiku',
    description: 'Documents allergies and reactions',
    canConsult: ['history_chief', 'history_meds'],
    reportsTo: 'history_chief',
  },
  'history_social': {
    id: 'history_social',
    name: 'Social History Gatherer',
    team: 'history',
    tier: 'worker',
    model: 'haiku',
    description: 'Collects smoking, alcohol, drug use, living situation',
    canConsult: ['history_chief'],
    reportsTo: 'history_chief',
  },
  'history_family': {
    id: 'history_family',
    name: 'Family History Collector',
    team: 'history',
    tier: 'worker',
    model: 'haiku',
    description: 'Documents family medical history',
    canConsult: ['history_chief'],
    reportsTo: 'history_chief',
  },
  'history_ros': {
    id: 'history_ros',
    name: 'Review of Systems',
    team: 'history',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Systematic review of all body systems',
    canConsult: ['history_chief', 'history_hpi', 'diff_chief'],
    reportsTo: 'history_chief',
  },
  'history_surgical': {
    id: 'history_surgical',
    name: 'Surgical History',
    team: 'history',
    tier: 'worker',
    model: 'haiku',
    description: 'Documents past surgeries and procedures',
    canConsult: ['history_chief'],
    reportsTo: 'history_chief',
  },
  'history_psych': {
    id: 'history_psych',
    name: 'Psychiatric History',
    team: 'history',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Sensitive mental health history gathering',
    canConsult: ['history_chief', 'safety_psych'],
    reportsTo: 'history_chief',
  },
  'history_ob': {
    id: 'history_ob',
    name: 'OB/GYN History',
    team: 'history',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Obstetric and gynecological history',
    canConsult: ['history_chief', 'safety_ob'],
    reportsTo: 'history_chief',
  },
  'history_peds': {
    id: 'history_peds',
    name: 'Pediatric History',
    team: 'history',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Child-specific history (milestones, vaccines)',
    canConsult: ['history_chief', 'safety_peds'],
    reportsTo: 'history_chief',
  },
  'history_travel': {
    id: 'history_travel',
    name: 'Travel History',
    team: 'history',
    tier: 'worker',
    model: 'haiku',
    description: 'Recent travel for infectious disease risk',
    canConsult: ['history_chief'],
    reportsTo: 'history_chief',
  },
  'history_occupational': {
    id: 'history_occupational',
    name: 'Occupational History',
    team: 'history',
    tier: 'worker',
    model: 'haiku',
    description: 'Work-related exposures and hazards',
    canConsult: ['history_chief'],
    reportsTo: 'history_chief',
  },

  // ============================================
  // TRIAGE TEAM (12 agents)
  // ============================================
  'triage_chief': {
    id: 'triage_chief',
    name: 'Triage Coordinator',
    team: 'triage',
    tier: 'supervisor',
    model: 'opus',
    description: 'Coordinates acuity assessment, makes final ESI decision',
    canConsult: ['orch_master', 'history_chief', 'safety_chief', 'diff_chief'],
    supervises: ['triage_esi', 'triage_acuity', 'triage_resource', 'triage_disposition', 'triage_pediatric', 'triage_geriatric', 'triage_ob', 'triage_psych', 'triage_trauma', 'triage_cardiac', 'triage_neuro'],
  },
  'triage_esi': {
    id: 'triage_esi',
    name: 'ESI Calculator',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Calculates Emergency Severity Index (1-5)',
    canConsult: ['triage_chief', 'triage_acuity', 'triage_resource'],
    reportsTo: 'triage_chief',
  },
  'triage_acuity': {
    id: 'triage_acuity',
    name: 'Acuity Assessor',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Assesses clinical urgency and time-sensitivity',
    canConsult: ['triage_chief', 'triage_esi'],
    reportsTo: 'triage_chief',
  },
  'triage_resource': {
    id: 'triage_resource',
    name: 'Resource Estimator',
    team: 'triage',
    tier: 'worker',
    model: 'haiku',
    description: 'Estimates resources needed for evaluation',
    canConsult: ['triage_chief'],
    reportsTo: 'triage_chief',
  },
  'triage_disposition': {
    id: 'triage_disposition',
    name: 'Disposition Recommender',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Recommends care setting (ED, urgent care, PCP, etc)',
    canConsult: ['triage_chief', 'triage_esi', 'plan_chief'],
    reportsTo: 'triage_chief',
  },
  'triage_pediatric': {
    id: 'triage_pediatric',
    name: 'Pediatric Triage Specialist',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Child-specific triage considerations',
    canConsult: ['triage_chief', 'safety_peds'],
    reportsTo: 'triage_chief',
  },
  'triage_geriatric': {
    id: 'triage_geriatric',
    name: 'Geriatric Triage Specialist',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Elderly-specific triage (atypical presentations)',
    canConsult: ['triage_chief', 'safety_elderly'],
    reportsTo: 'triage_chief',
  },
  'triage_ob': {
    id: 'triage_ob',
    name: 'OB Triage Specialist',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Pregnancy-specific triage',
    canConsult: ['triage_chief', 'safety_ob'],
    reportsTo: 'triage_chief',
  },
  'triage_psych': {
    id: 'triage_psych',
    name: 'Psychiatric Triage Specialist',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Mental health triage, suicide risk assessment',
    canConsult: ['triage_chief', 'safety_psych'],
    reportsTo: 'triage_chief',
  },
  'triage_trauma': {
    id: 'triage_trauma',
    name: 'Trauma Triage Specialist',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Injury and trauma triage',
    canConsult: ['triage_chief', 'safety_trauma'],
    reportsTo: 'triage_chief',
  },
  'triage_cardiac': {
    id: 'triage_cardiac',
    name: 'Cardiac Triage Specialist',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Chest pain and cardiac symptom triage',
    canConsult: ['triage_chief', 'safety_cardiac'],
    reportsTo: 'triage_chief',
  },
  'triage_neuro': {
    id: 'triage_neuro',
    name: 'Neuro Triage Specialist',
    team: 'triage',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Neurological symptom triage (stroke, seizure)',
    canConsult: ['triage_chief', 'safety_neuro'],
    reportsTo: 'triage_chief',
  },

  // ============================================
  // DIFFERENTIAL DIAGNOSIS TEAM (18 agents)
  // ============================================
  'diff_chief': {
    id: 'diff_chief',
    name: 'Differential Coordinator',
    team: 'differential',
    tier: 'supervisor',
    model: 'opus',
    description: 'Coordinates differential diagnosis, builds consensus',
    canConsult: ['orch_master', 'triage_chief', 'safety_chief', 'knowledge_chief'],
    supervises: ['diff_hypothesis', 'diff_evidence', 'diff_mustnotmiss', 'diff_consensus', 'diff_cardio', 'diff_pulm', 'diff_gi', 'diff_neuro', 'diff_msk', 'diff_derm', 'diff_endo', 'diff_heme', 'diff_id', 'diff_renal', 'diff_rheum', 'diff_psych', 'diff_peds'],
  },
  'diff_hypothesis': {
    id: 'diff_hypothesis',
    name: 'Hypothesis Generator',
    team: 'differential',
    tier: 'specialist',
    model: 'opus',
    description: 'Generates initial differential diagnosis list',
    canConsult: ['diff_chief', 'diff_evidence', 'knowledge_diagnosis'],
    reportsTo: 'diff_chief',
  },
  'diff_evidence': {
    id: 'diff_evidence',
    name: 'Evidence Weigher',
    team: 'differential',
    tier: 'specialist',
    model: 'opus',
    description: 'Weighs supporting/refuting evidence for each diagnosis',
    canConsult: ['diff_chief', 'diff_hypothesis', 'knowledge_literature'],
    reportsTo: 'diff_chief',
  },
  'diff_mustnotmiss': {
    id: 'diff_mustnotmiss',
    name: 'Must-Not-Miss Checker',
    team: 'differential',
    tier: 'specialist',
    model: 'opus',
    description: 'Ensures dangerous diagnoses are not overlooked',
    canConsult: ['diff_chief', 'safety_chief'],
    reportsTo: 'diff_chief',
  },
  'diff_consensus': {
    id: 'diff_consensus',
    name: 'Differential Consensus Builder',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Builds consensus from specialist opinions',
    canConsult: ['diff_chief', 'orch_consensus'],
    reportsTo: 'diff_chief',
  },
  // System-specific differential specialists
  'diff_cardio': {
    id: 'diff_cardio',
    name: 'Cardiology Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Cardiovascular differential diagnoses',
    canConsult: ['diff_chief', 'knowledge_cardio'],
    reportsTo: 'diff_chief',
  },
  'diff_pulm': {
    id: 'diff_pulm',
    name: 'Pulmonology Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Pulmonary differential diagnoses',
    canConsult: ['diff_chief', 'knowledge_pulm'],
    reportsTo: 'diff_chief',
  },
  'diff_gi': {
    id: 'diff_gi',
    name: 'GI Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Gastrointestinal differential diagnoses',
    canConsult: ['diff_chief', 'knowledge_gi'],
    reportsTo: 'diff_chief',
  },
  'diff_neuro': {
    id: 'diff_neuro',
    name: 'Neurology Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Neurological differential diagnoses',
    canConsult: ['diff_chief', 'knowledge_neuro'],
    reportsTo: 'diff_chief',
  },
  'diff_msk': {
    id: 'diff_msk',
    name: 'MSK Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Musculoskeletal differential diagnoses',
    canConsult: ['diff_chief'],
    reportsTo: 'diff_chief',
  },
  'diff_derm': {
    id: 'diff_derm',
    name: 'Dermatology Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Skin condition differential diagnoses',
    canConsult: ['diff_chief'],
    reportsTo: 'diff_chief',
  },
  'diff_endo': {
    id: 'diff_endo',
    name: 'Endocrine Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Endocrine/metabolic differential diagnoses',
    canConsult: ['diff_chief'],
    reportsTo: 'diff_chief',
  },
  'diff_heme': {
    id: 'diff_heme',
    name: 'Hematology Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Hematologic differential diagnoses',
    canConsult: ['diff_chief'],
    reportsTo: 'diff_chief',
  },
  'diff_id': {
    id: 'diff_id',
    name: 'Infectious Disease Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Infectious disease differential diagnoses',
    canConsult: ['diff_chief', 'knowledge_id'],
    reportsTo: 'diff_chief',
  },
  'diff_renal': {
    id: 'diff_renal',
    name: 'Nephrology Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Renal/urological differential diagnoses',
    canConsult: ['diff_chief'],
    reportsTo: 'diff_chief',
  },
  'diff_rheum': {
    id: 'diff_rheum',
    name: 'Rheumatology Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Rheumatologic differential diagnoses',
    canConsult: ['diff_chief'],
    reportsTo: 'diff_chief',
  },
  'diff_psych': {
    id: 'diff_psych',
    name: 'Psychiatry Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Psychiatric differential diagnoses',
    canConsult: ['diff_chief', 'safety_psych'],
    reportsTo: 'diff_chief',
  },
  'diff_peds': {
    id: 'diff_peds',
    name: 'Pediatric Differential',
    team: 'differential',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Pediatric-specific differential diagnoses',
    canConsult: ['diff_chief', 'safety_peds'],
    reportsTo: 'diff_chief',
  },

  // ============================================
  // SAFETY TEAM (15 agents) - CRITICAL
  // ============================================
  'safety_chief': {
    id: 'safety_chief',
    name: 'Safety Coordinator',
    team: 'safety',
    tier: 'supervisor',
    model: 'opus',
    description: 'Master safety monitor, can override any decision',
    canConsult: ['orch_master', 'triage_chief', 'diff_chief'],
    supervises: ['safety_cardiac', 'safety_neuro', 'safety_resp', 'safety_psych', 'safety_peds', 'safety_ob', 'safety_elderly', 'safety_trauma', 'safety_drug', 'safety_allergy', 'safety_sepsis', 'safety_abuse', 'safety_suicide', 'safety_override'],
  },
  'safety_cardiac': {
    id: 'safety_cardiac',
    name: 'Cardiac Red Flag Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for MI, arrhythmia, aortic emergency',
    canConsult: ['safety_chief', 'triage_cardiac'],
    reportsTo: 'safety_chief',
  },
  'safety_neuro': {
    id: 'safety_neuro',
    name: 'Neuro Red Flag Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for stroke, meningitis, increased ICP',
    canConsult: ['safety_chief', 'triage_neuro'],
    reportsTo: 'safety_chief',
  },
  'safety_resp': {
    id: 'safety_resp',
    name: 'Respiratory Red Flag Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for PE, respiratory failure, anaphylaxis',
    canConsult: ['safety_chief'],
    reportsTo: 'safety_chief',
  },
  'safety_psych': {
    id: 'safety_psych',
    name: 'Psychiatric Safety Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'opus',
    description: 'Monitors for suicidal ideation, psychosis, violence risk',
    canConsult: ['safety_chief', 'triage_psych', 'safety_suicide'],
    reportsTo: 'safety_chief',
  },
  'safety_peds': {
    id: 'safety_peds',
    name: 'Pediatric Safety Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for child-specific emergencies, abuse',
    canConsult: ['safety_chief', 'triage_pediatric', 'safety_abuse'],
    reportsTo: 'safety_chief',
  },
  'safety_ob': {
    id: 'safety_ob',
    name: 'OB Safety Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for ectopic, preeclampsia, placental abruption',
    canConsult: ['safety_chief', 'triage_ob'],
    reportsTo: 'safety_chief',
  },
  'safety_elderly': {
    id: 'safety_elderly',
    name: 'Geriatric Safety Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for atypical presentations in elderly',
    canConsult: ['safety_chief', 'triage_geriatric'],
    reportsTo: 'safety_chief',
  },
  'safety_trauma': {
    id: 'safety_trauma',
    name: 'Trauma Safety Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for occult trauma, internal bleeding',
    canConsult: ['safety_chief', 'triage_trauma'],
    reportsTo: 'safety_chief',
  },
  'safety_drug': {
    id: 'safety_drug',
    name: 'Drug Interaction Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for dangerous drug interactions',
    canConsult: ['safety_chief', 'history_meds', 'knowledge_drugs'],
    reportsTo: 'safety_chief',
  },
  'safety_allergy': {
    id: 'safety_allergy',
    name: 'Allergy Safety Monitor',
    team: 'safety',
    tier: 'worker',
    model: 'haiku',
    description: 'Monitors for allergen exposure, anaphylaxis risk',
    canConsult: ['safety_chief', 'history_allergy'],
    reportsTo: 'safety_chief',
  },
  'safety_sepsis': {
    id: 'safety_sepsis',
    name: 'Sepsis Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Monitors for sepsis criteria and early warning signs',
    canConsult: ['safety_chief'],
    reportsTo: 'safety_chief',
  },
  'safety_abuse': {
    id: 'safety_abuse',
    name: 'Abuse Detection Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'opus',
    description: 'Monitors for signs of abuse (child, elder, domestic)',
    canConsult: ['safety_chief', 'safety_peds'],
    reportsTo: 'safety_chief',
  },
  'safety_suicide': {
    id: 'safety_suicide',
    name: 'Suicide Risk Monitor',
    team: 'safety',
    tier: 'specialist',
    model: 'opus',
    description: 'Dedicated suicide risk assessment',
    canConsult: ['safety_chief', 'safety_psych'],
    reportsTo: 'safety_chief',
  },
  'safety_override': {
    id: 'safety_override',
    name: 'Safety Override Controller',
    team: 'safety',
    tier: 'specialist',
    model: 'opus',
    description: 'Can override any agent decision for safety',
    canConsult: ['safety_chief', 'orch_master'],
    reportsTo: 'safety_chief',
  },

  // ============================================
  // PLAN TEAM (10 agents)
  // ============================================
  'plan_chief': {
    id: 'plan_chief',
    name: 'Plan Coordinator',
    team: 'plan',
    tier: 'supervisor',
    model: 'sonnet',
    description: 'Coordinates care plan development',
    canConsult: ['orch_master', 'diff_chief', 'triage_chief'],
    supervises: ['plan_workup', 'plan_referral', 'plan_education', 'plan_followup', 'plan_rx', 'plan_preventive', 'plan_lifestyle', 'plan_urgent', 'plan_home'],
  },
  'plan_workup': {
    id: 'plan_workup',
    name: 'Workup Planner',
    team: 'plan',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Plans diagnostic tests and imaging',
    canConsult: ['plan_chief', 'diff_chief'],
    reportsTo: 'plan_chief',
  },
  'plan_referral': {
    id: 'plan_referral',
    name: 'Referral Recommender',
    team: 'plan',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Recommends specialist referrals',
    canConsult: ['plan_chief', 'booking_chief'],
    reportsTo: 'plan_chief',
  },
  'plan_education': {
    id: 'plan_education',
    name: 'Patient Educator',
    team: 'plan',
    tier: 'worker',
    model: 'haiku',
    description: 'Creates patient education materials',
    canConsult: ['plan_chief'],
    reportsTo: 'plan_chief',
  },
  'plan_followup': {
    id: 'plan_followup',
    name: 'Follow-up Planner',
    team: 'plan',
    tier: 'worker',
    model: 'haiku',
    description: 'Plans follow-up care and monitoring',
    canConsult: ['plan_chief'],
    reportsTo: 'plan_chief',
  },
  'plan_rx': {
    id: 'plan_rx',
    name: 'Medication Recommender',
    team: 'plan',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Recommends medications (not prescribes)',
    canConsult: ['plan_chief', 'safety_drug', 'knowledge_drugs'],
    reportsTo: 'plan_chief',
  },
  'plan_preventive': {
    id: 'plan_preventive',
    name: 'Preventive Care Advisor',
    team: 'plan',
    tier: 'worker',
    model: 'haiku',
    description: 'Recommends screenings and preventive measures',
    canConsult: ['plan_chief'],
    reportsTo: 'plan_chief',
  },
  'plan_lifestyle': {
    id: 'plan_lifestyle',
    name: 'Lifestyle Advisor',
    team: 'plan',
    tier: 'worker',
    model: 'haiku',
    description: 'Lifestyle modification recommendations',
    canConsult: ['plan_chief'],
    reportsTo: 'plan_chief',
  },
  'plan_urgent': {
    id: 'plan_urgent',
    name: 'Urgent Care Coordinator',
    team: 'plan',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Coordinates urgent/emergent care needs',
    canConsult: ['plan_chief', 'triage_chief'],
    reportsTo: 'plan_chief',
  },
  'plan_home': {
    id: 'plan_home',
    name: 'Home Care Advisor',
    team: 'plan',
    tier: 'worker',
    model: 'haiku',
    description: 'Home care and self-management instructions',
    canConsult: ['plan_chief'],
    reportsTo: 'plan_chief',
  },

  // ============================================
  // DOCUMENTATION TEAM (8 agents)
  // ============================================
  'doc_chief': {
    id: 'doc_chief',
    name: 'Documentation Coordinator',
    team: 'documentation',
    tier: 'supervisor',
    model: 'sonnet',
    description: 'Coordinates clinical documentation',
    canConsult: ['orch_master', 'history_chief', 'diff_chief'],
    supervises: ['doc_soap', 'doc_summary', 'doc_handoff', 'doc_icd', 'doc_cpt', 'doc_letter', 'doc_discharge'],
  },
  'doc_soap': {
    id: 'doc_soap',
    name: 'SOAP Note Writer',
    team: 'documentation',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Generates SOAP format clinical notes',
    canConsult: ['doc_chief', 'history_chief'],
    reportsTo: 'doc_chief',
  },
  'doc_summary': {
    id: 'doc_summary',
    name: 'Summary Generator',
    team: 'documentation',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Creates patient-friendly summaries',
    canConsult: ['doc_chief'],
    reportsTo: 'doc_chief',
  },
  'doc_handoff': {
    id: 'doc_handoff',
    name: 'Handoff Creator',
    team: 'documentation',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Creates clinical handoff documents',
    canConsult: ['doc_chief', 'booking_chief'],
    reportsTo: 'doc_chief',
  },
  'doc_icd': {
    id: 'doc_icd',
    name: 'ICD Coder',
    team: 'documentation',
    tier: 'worker',
    model: 'haiku',
    description: 'Assigns ICD-10 diagnosis codes',
    canConsult: ['doc_chief', 'knowledge_icd'],
    reportsTo: 'doc_chief',
  },
  'doc_cpt': {
    id: 'doc_cpt',
    name: 'CPT Coder',
    team: 'documentation',
    tier: 'worker',
    model: 'haiku',
    description: 'Assigns CPT procedure codes',
    canConsult: ['doc_chief'],
    reportsTo: 'doc_chief',
  },
  'doc_letter': {
    id: 'doc_letter',
    name: 'Referral Letter Writer',
    team: 'documentation',
    tier: 'worker',
    model: 'haiku',
    description: 'Writes referral letters',
    canConsult: ['doc_chief', 'plan_referral'],
    reportsTo: 'doc_chief',
  },
  'doc_discharge': {
    id: 'doc_discharge',
    name: 'Discharge Instructions',
    team: 'documentation',
    tier: 'worker',
    model: 'haiku',
    description: 'Creates discharge/care instructions',
    canConsult: ['doc_chief', 'plan_education'],
    reportsTo: 'doc_chief',
  },

  // ============================================
  // BOOKING TEAM (6 agents)
  // ============================================
  'booking_chief': {
    id: 'booking_chief',
    name: 'Booking Coordinator',
    team: 'booking',
    tier: 'supervisor',
    model: 'sonnet',
    description: 'Coordinates appointment scheduling',
    canConsult: ['orch_master', 'plan_chief'],
    supervises: ['booking_match', 'booking_avail', 'booking_schedule', 'booking_insurance', 'booking_confirm'],
  },
  'booking_match': {
    id: 'booking_match',
    name: 'Provider Matcher',
    team: 'booking',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Matches patient needs to provider specialty',
    canConsult: ['booking_chief', 'plan_referral'],
    reportsTo: 'booking_chief',
  },
  'booking_avail': {
    id: 'booking_avail',
    name: 'Availability Checker',
    team: 'booking',
    tier: 'worker',
    model: 'haiku',
    description: 'Checks provider availability',
    canConsult: ['booking_chief'],
    reportsTo: 'booking_chief',
  },
  'booking_schedule': {
    id: 'booking_schedule',
    name: 'Appointment Scheduler',
    team: 'booking',
    tier: 'worker',
    model: 'haiku',
    description: 'Books appointments',
    canConsult: ['booking_chief'],
    reportsTo: 'booking_chief',
  },
  'booking_insurance': {
    id: 'booking_insurance',
    name: 'Insurance Verifier',
    team: 'booking',
    tier: 'worker',
    model: 'haiku',
    description: 'Verifies insurance coverage',
    canConsult: ['booking_chief'],
    reportsTo: 'booking_chief',
  },
  'booking_confirm': {
    id: 'booking_confirm',
    name: 'Confirmation Sender',
    team: 'booking',
    tier: 'worker',
    model: 'haiku',
    description: 'Sends booking confirmations',
    canConsult: ['booking_chief'],
    reportsTo: 'booking_chief',
  },

  // ============================================
  // KNOWLEDGE TEAM (10 agents)
  // ============================================
  'knowledge_chief': {
    id: 'knowledge_chief',
    name: 'Knowledge Coordinator',
    team: 'knowledge',
    tier: 'supervisor',
    model: 'sonnet',
    description: 'Coordinates knowledge base queries',
    canConsult: ['orch_master', 'diff_chief'],
    supervises: ['knowledge_drugs', 'knowledge_icd', 'knowledge_diagnosis', 'knowledge_literature', 'knowledge_guidelines', 'knowledge_cardio', 'knowledge_pulm', 'knowledge_gi', 'knowledge_neuro', 'knowledge_id'],
  },
  'knowledge_drugs': {
    id: 'knowledge_drugs',
    name: 'Drug Knowledge Agent',
    team: 'knowledge',
    tier: 'specialist',
    model: 'sonnet',
    description: 'RxNorm queries, drug interactions',
    canConsult: ['knowledge_chief', 'safety_drug'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_icd': {
    id: 'knowledge_icd',
    name: 'ICD Knowledge Agent',
    team: 'knowledge',
    tier: 'worker',
    model: 'haiku',
    description: 'ICD-10 code lookups',
    canConsult: ['knowledge_chief', 'doc_icd'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_diagnosis': {
    id: 'knowledge_diagnosis',
    name: 'Diagnosis Knowledge Agent',
    team: 'knowledge',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Diagnosis criteria and guidelines',
    canConsult: ['knowledge_chief', 'diff_chief'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_literature': {
    id: 'knowledge_literature',
    name: 'Literature Search Agent',
    team: 'knowledge',
    tier: 'specialist',
    model: 'sonnet',
    description: 'PubMed and clinical literature search',
    canConsult: ['knowledge_chief', 'diff_evidence'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_guidelines': {
    id: 'knowledge_guidelines',
    name: 'Clinical Guidelines Agent',
    team: 'knowledge',
    tier: 'specialist',
    model: 'sonnet',
    description: 'Clinical practice guidelines',
    canConsult: ['knowledge_chief', 'plan_chief'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_cardio': {
    id: 'knowledge_cardio',
    name: 'Cardiology Knowledge',
    team: 'knowledge',
    tier: 'worker',
    model: 'haiku',
    description: 'Cardiology-specific knowledge',
    canConsult: ['knowledge_chief', 'diff_cardio'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_pulm': {
    id: 'knowledge_pulm',
    name: 'Pulmonology Knowledge',
    team: 'knowledge',
    tier: 'worker',
    model: 'haiku',
    description: 'Pulmonology-specific knowledge',
    canConsult: ['knowledge_chief', 'diff_pulm'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_gi': {
    id: 'knowledge_gi',
    name: 'GI Knowledge',
    team: 'knowledge',
    tier: 'worker',
    model: 'haiku',
    description: 'Gastroenterology-specific knowledge',
    canConsult: ['knowledge_chief', 'diff_gi'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_neuro': {
    id: 'knowledge_neuro',
    name: 'Neurology Knowledge',
    team: 'knowledge',
    tier: 'worker',
    model: 'haiku',
    description: 'Neurology-specific knowledge',
    canConsult: ['knowledge_chief', 'diff_neuro'],
    reportsTo: 'knowledge_chief',
  },
  'knowledge_id': {
    id: 'knowledge_id',
    name: 'Infectious Disease Knowledge',
    team: 'knowledge',
    tier: 'worker',
    model: 'haiku',
    description: 'Infectious disease knowledge',
    canConsult: ['knowledge_chief', 'diff_id'],
    reportsTo: 'knowledge_chief',
  },
};

// Validate agent count
export const AGENT_COUNT = Object.keys(AGENT_REGISTRY).length;

// Helper functions
export function getAgentById(id: string): AgentDefinition | undefined {
  return AGENT_REGISTRY[id];
}

export function getAgentsByTeam(team: AgentTeam): AgentDefinition[] {
  return Object.values(AGENT_REGISTRY).filter(a => a.team === team);
}

export function getSupervisorAgents(): AgentDefinition[] {
  return Object.values(AGENT_REGISTRY).filter(a => a.tier === 'supervisor');
}

export function getSubordinates(supervisorId: string): AgentDefinition[] {
  const supervisor = AGENT_REGISTRY[supervisorId];
  if (!supervisor?.supervises) return [];
  return supervisor.supervises.map(id => AGENT_REGISTRY[id]).filter(Boolean);
}

export function canAgentConsult(fromId: string, toId: string): boolean {
  const from = AGENT_REGISTRY[fromId];
  return from?.canConsult?.includes(toId) ?? false;
}

export function getAgentsByTier(tier: AgentTier): AgentDefinition[] {
  return Object.values(AGENT_REGISTRY).filter(a => a.tier === tier);
}

export function getAgentsByModel(model: 'opus' | 'sonnet' | 'haiku'): AgentDefinition[] {
  return Object.values(AGENT_REGISTRY).filter(a => a.model === model);
}
