/**
 * SOAP Note Writer Agent
 * Generates structured clinical documentation
 */

import Anthropic from '@anthropic-ai/sdk';
import { BaseAgent } from '../base.js';
import type { AgentConfig, AgentContext, AgentOutput } from '../types.js';
import type { SupportedLanguage } from '../../config/languages.js';
import { CLAUDE_MODELS } from '../../config/models.js';

const PROMPTS: Record<SupportedLanguage, string> = {
  en: `You are the SOAP Note Writer for HELIOS clinical triage.

## YOUR TASK
Generate a structured SOAP note summarizing the clinical encounter.

## SOAP FORMAT

### SUBJECTIVE
- Chief Complaint
- History of Present Illness (OLDCARTS)
- Past Medical History
- Medications
- Allergies
- Social History
- Family History
- Review of Systems

### OBJECTIVE
- Vital signs (if available)
- Patient-reported physical findings
- Relevant observations from conversation

### ASSESSMENT
- Differential CONSIDERATIONS (not diagnoses)
- Risk stratification
- Red flags identified
- Triage level assigned

### PLAN
- Recommended disposition
- Recommended workup (if applicable)
- Warning signs to watch for
- Follow-up recommendations
- Patient education provided

## OUTPUT FORMAT (JSON)
{
  "soap_note": {
    "subjective": {
      "chief_complaint": "...",
      "hpi": "...",
      "pmh": ["..."],
      "medications": ["..."],
      "allergies": ["..."],
      "social_history": "...",
      "family_history": "...",
      "ros": "..."
    },
    "objective": {
      "vitals": "...",
      "observations": "..."
    },
    "assessment": {
      "differential": ["..."],
      "risk_level": "...",
      "red_flags": ["..."],
      "triage_level": "ESI1-5"
    },
    "plan": {
      "disposition": "...",
      "workup": ["..."],
      "warning_signs": ["..."],
      "follow_up": "...",
      "education": "..."
    }
  },
  "ai_disclaimer": "This note was generated by an AI clinical support system...",
  "confidence": 0.0-1.0
}

## RULES
- Use "considerations" not "diagnoses"
- Include AI disclaimer
- List red flags prominently
- Be concise but complete`,

  es: `Eres el Escritor de Notas SOAP para el triaje clínico de HELIOS.

## TU TAREA
Generar una nota SOAP estructurada resumiendo el encuentro clínico.

## FORMATO SOAP

### SUBJETIVO
- Motivo de Consulta
- Historia de la Enfermedad Actual
- Antecedentes Médicos
- Medicamentos
- Alergias

### OBJETIVO
- Signos vitales
- Observaciones

### EVALUACIÓN
- Consideraciones diagnósticas
- Nivel de riesgo
- Banderas rojas

### PLAN
- Disposición recomendada
- Señales de alarma
- Seguimiento

## FORMATO DE SALIDA (JSON)
{
  "soap_note": { ... },
  "ai_disclaimer": "Esta nota fue generada por un sistema de IA...",
  "confidence": 0.0-1.0
}`,

  fr: `Vous êtes le Rédacteur de Notes SOAP pour le triage clinique HELIOS.

## VOTRE TÂCHE
Générer une note SOAP structurée résumant la rencontre clinique.

## FORMAT SOAP

### SUBJECTIF
- Motif de Consultation
- Histoire de la Maladie Actuelle
- Antécédents Médicaux
- Médicaments
- Allergies

### OBJECTIF
- Signes vitaux
- Observations

### ÉVALUATION
- Considérations diagnostiques
- Niveau de risque
- Drapeaux rouges

### PLAN
- Disposition recommandée
- Signes d'alarme
- Suivi

## FORMAT DE SORTIE (JSON)
{
  "soap_note": { ... },
  "ai_disclaimer": "Cette note a été générée par un système d'IA...",
  "confidence": 0.0-1.0
}`,
};

const AI_DISCLAIMERS: Record<SupportedLanguage, string> = {
  en: "This clinical note was generated by an AI clinical support system (HELIOS) and is intended for educational and triage support purposes only. It does not constitute medical advice, diagnosis, or treatment. All information should be verified by a licensed healthcare provider. The patient should seek professional medical evaluation for proper diagnosis and treatment.",
  es: "Esta nota clínica fue generada por un sistema de apoyo clínico de IA (HELIOS) y está destinada únicamente para fines educativos y de apoyo al triaje. No constituye consejo médico, diagnóstico o tratamiento. Toda la información debe ser verificada por un profesional de la salud. El paciente debe buscar evaluación médica profesional.",
  fr: "Cette note clinique a été générée par un système de support clinique IA (HELIOS) et est destinée uniquement à des fins éducatives et de support au triage. Elle ne constitue pas un avis médical, un diagnostic ou un traitement. Toutes les informations doivent être vérifiées par un professionnel de santé.",
};

export class SOAPWriterAgent extends BaseAgent {
  constructor(client: Anthropic) {
    const config: AgentConfig = {
      id: 'soap_writer_001',
      role: 'soap_writer',
      team: 'documentation',
      name: 'SOAP Note Writer',
      description: 'Generates structured clinical documentation',
      model: CLAUDE_MODELS.SONNET_4_5,
      maxTokens: 4096,
      temperature: 0.2,
      systemPrompt: '',
      requiredPhases: ['documentation'],
      priority: 1,
    };
    super(config, client);
  }

  getSystemPrompt(language: SupportedLanguage): string {
    return PROMPTS[language];
  }

  parseOutput(response: string, context: AgentContext): Partial<AgentOutput> {
    try {
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (!jsonMatch) return { confidence: 0.5 };

      const parsed = JSON.parse(jsonMatch[0]) as {
        ai_disclaimer?: string;
        confidence?: number;
      };

      // Ensure AI disclaimer is included
      if (!parsed.ai_disclaimer) {
        parsed.ai_disclaimer = AI_DISCLAIMERS[context.language];
      }

      return {
        structuredOutput: parsed,
        confidence: parsed.confidence || 0.9,
        recommendedPhase: 'completed',
      };
    } catch {
      return { confidence: 0.5 };
    }
  }
}
