/**
 * Health Session Panel - Local storage management for health conversations
 * Features: Transcription storage, download, delete, export for doctor
 */

import { useState, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import {
  Download,
  Trash2,
  FileText,
  Clock,
  ChevronDown,
  ChevronUp,
  Share2,
  Shield,
  HardDrive,
  AlertTriangle,
  CheckCircle2,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';

// Use a flexible type that works with ConversationSummary
interface ConversationItem {
  id: string;
  title: string;
  messageCount: number;
  updatedAt: number;
  retentionMode?: string;
  taskType?: string;
}

interface HealthSessionPanelProps {
  conversations: ConversationItem[];
  onDeleteSession: (id: string) => Promise<void>;
  onSelectSession: (id: string) => void;
  selectedSessionId?: string;
  className?: string;
}

export function HealthSessionPanel({
  conversations,
  onDeleteSession,
  onSelectSession,
  selectedSessionId,
  className
}: HealthSessionPanelProps) {
  const { t } = useTranslation();
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  // Generate transcript text from conversation summary
  const generateTranscript = useCallback((conv: ConversationItem): string => {
    const header = [
      '═══════════════════════════════════════════════════════════════',
      '                    HEALTH CONSULTATION TRANSCRIPT',
      '═══════════════════════════════════════════════════════════════',
      '',
      `Session ID: ${conv.id}`,
      `Title: ${conv.title}`,
      `Last Updated: ${format(new Date(conv.updatedAt), 'PPpp')}`,
      `Type: ${conv.taskType || 'general_query'}`,
      `Messages: ${conv.messageCount}`,
      '',
      '═══════════════════════════════════════════════════════════════',
      '',
      'Note: Full transcript requires loading the complete session.',
      '',
      '═══════════════════════════════════════════════════════════════',
      '                          DISCLAIMER',
      '═══════════════════════════════════════════════════════════════',
      '',
      'This transcript was generated by an AI healthcare assistant for',
      'informational purposes only. It does NOT constitute medical advice.',
      '',
      'Data stored locally on your device with AES-256-GCM encryption.',
      '',
      '═══════════════════════════════════════════════════════════════',
    ].join('\n');

    return header;
  }, []);

  // Download session as text file
  const handleDownload = useCallback(async (conv: ConversationItem) => {
    setDownloadingId(conv.id);
    try {
      const transcript = generateTranscript(conv);
      const blob = new Blob([transcript], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `health-session-${format(new Date(conv.updatedAt), 'yyyy-MM-dd-HHmm')}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } finally {
      setDownloadingId(null);
    }
  }, [generateTranscript]);

  // Export as JSON for doctor
  const handleExportForDoctor = useCallback((conv: ConversationItem) => {
    const exportData = {
      exportedAt: new Date().toISOString(),
      session: {
        id: conv.id,
        title: conv.title,
        lastUpdated: new Date(conv.updatedAt).toISOString(),
        type: conv.taskType || 'general_query',
        messageCount: conv.messageCount,
      },
      disclaimer: 'AI-generated content for informational purposes only. Not medical advice.',
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `health-export-${format(new Date(conv.updatedAt), 'yyyy-MM-dd')}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, []);

  // Delete session
  const handleDelete = useCallback(async (id: string) => {
    if (!confirm(t('ghost.health.sessions.confirmDelete', 'Are you sure you want to delete this session? This cannot be undone.'))) {
      return;
    }
    setDeletingId(id);
    try {
      await onDeleteSession(id);
    } finally {
      setDeletingId(null);
    }
  }, [onDeleteSession, t]);

  if (conversations.length === 0) {
    return (
      <Card className={cn("p-6 text-center", className)}>
        <HardDrive className="w-10 h-10 mx-auto text-slate-300 mb-3" />
        <h3 className="font-medium text-slate-600 mb-1">
          {t('ghost.health.sessions.noSessions', 'No Health Sessions')}
        </h3>
        <p className="text-sm text-slate-400">
          {t('ghost.health.sessions.noSessionsDesc', 'Your health conversations will be stored locally on your device.')}
        </p>
        <div className="mt-4 flex items-center justify-center gap-2 text-xs text-emerald-600">
          <Shield className="w-3.5 h-3.5" />
          <span>{t('ghost.health.sessions.encrypted', 'AES-256 Encrypted')}</span>
        </div>
      </Card>
    );
  }

  return (
    <Card className={cn("overflow-hidden", className)}>
      <div className="p-4 border-b border-slate-100 bg-slate-50">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-[#2A8C86]" />
            <h3 className="font-medium text-slate-800">
              {t('ghost.health.sessions.title', 'Health Sessions')}
            </h3>
            <Badge variant="secondary" className="text-xs">
              {conversations.length}
            </Badge>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-emerald-600">
            <Shield className="w-3.5 h-3.5" />
            <span>{t('ghost.health.sessions.localOnly', 'Stored Locally')}</span>
          </div>
        </div>
      </div>

      <ScrollArea className="max-h-[400px]">
        <div className="divide-y divide-slate-100">
          {conversations.map((conv) => (
            <div
              key={conv.id}
              className={cn(
                "p-3 transition-colors",
                selectedSessionId === conv.id ? "bg-[#2A8C86]/5" : "hover:bg-slate-50"
              )}
            >
              <div 
                className="flex items-start justify-between cursor-pointer"
                onClick={() => {
                  onSelectSession(conv.id);
                  setExpandedId(expandedId === conv.id ? null : conv.id);
                }}
              >
                <div className="flex-1 min-w-0">
                  <h4 className="font-medium text-sm text-slate-800 truncate">
                    {conv.title}
                  </h4>
                  <div className="flex items-center gap-2 mt-1 text-xs text-slate-500">
                    <Clock className="w-3 h-3" />
                    <span>{format(new Date(conv.updatedAt), 'MMM d, yyyy h:mm a')}</span>
                    <span>•</span>
                    <span>{conv.messageCount} messages</span>
                  </div>
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-6 w-6 text-slate-400"
                >
                  {expandedId === conv.id ? (
                    <ChevronUp className="w-4 h-4" />
                  ) : (
                    <ChevronDown className="w-4 h-4" />
                  )}
                </Button>
              </div>

              {/* Expanded Actions */}
              {expandedId === conv.id && (
                <div className="mt-3 pt-3 border-t border-slate-100 space-y-3">
                  {/* Session Info */}
                  <div className="p-2 bg-slate-50 rounded text-xs text-slate-600">
                    {conv.messageCount} messages • Last updated {new Date(conv.updatedAt).toLocaleString()}
                  </div>

                  {/* Retention Badge */}
                  <div className="flex items-center gap-2">
                    {conv.retentionMode && (
                      <Badge variant={conv.retentionMode === 'forever' ? 'default' : 'secondary'} className="text-xs">
                        {conv.retentionMode === 'forever' && <CheckCircle2 className="w-3 h-3 mr-1" />}
                        {conv.retentionMode === 'zerotrace' && <AlertTriangle className="w-3 h-3 mr-1" />}
                        {conv.retentionMode}
                      </Badge>
                    )}
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-2 flex-wrap">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDownload(conv);
                      }}
                      disabled={downloadingId === conv.id}
                      className="h-8 text-xs gap-1.5"
                    >
                      <Download className="w-3.5 h-3.5" />
                      {t('ghost.health.sessions.download', 'Download')}
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleExportForDoctor(conv);
                      }}
                      className="h-8 text-xs gap-1.5 text-emerald-700 border-emerald-200 hover:bg-emerald-50"
                    >
                      <Share2 className="w-3.5 h-3.5" />
                      {t('ghost.health.sessions.exportForDoctor', 'Export for Doctor')}
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDelete(conv.id);
                      }}
                      disabled={deletingId === conv.id}
                      className="h-8 text-xs gap-1.5 text-red-600 border-red-200 hover:bg-red-50"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                      {t('ghost.health.sessions.delete', 'Delete')}
                    </Button>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </ScrollArea>

      {/* Footer */}
      <div className="p-3 bg-slate-50 border-t border-slate-100">
        <p className="text-[10px] text-slate-500 text-center">
          {t('ghost.health.sessions.storageNote', 'All data encrypted and stored on your device only. Never sent to servers.')}
        </p>
      </div>
    </Card>
  );
}
