/**
 * HELIOS SOAP Note PDF Generator
 *
 * Generates a professional PDF document from SOAP note data
 * for patient records and healthcare provider handoff.
 */

import { jsPDF } from 'jspdf';

interface SOAPData {
  subjective: string | string[];
  objective: string | string[];
  assessment: string | string[];
  plan: string | string[];
}

interface SessionInfo {
  sessionId: string;
  chiefComplaint?: string;
  patient?: {
    age?: number | string;
    sex?: string;
  };
  triageLevel?: number;
  disposition?: string;
  consultDate?: string;
  expertCount?: number;
  agreementScore?: number;
  redFlags?: string[];
}

interface PDFOptions {
  includeDisclaimer?: boolean;
  includeMetadata?: boolean;
  language?: 'en' | 'es' | 'fr';
}

const TRANSLATIONS = {
  en: {
    title: 'SOAP Note',
    subtitle: 'HELIOS AI Health Consultation',
    generated: 'Generated',
    sessionId: 'Session ID',
    patient: 'Patient',
    age: 'Age',
    sex: 'Sex',
    chiefComplaint: 'Chief Complaint',
    triageLevel: 'Triage Level (ESI)',
    disposition: 'Disposition',
    subjective: 'Subjective',
    objective: 'Objective',
    assessment: 'Assessment',
    plan: 'Plan',
    redFlags: 'Red Flags / Warnings',
    disclaimer: 'This AI-generated summary is for informational purposes only and does not constitute medical advice. Please consult with a licensed healthcare provider.',
    footer: 'Generated by HELIOS AI Health Assistant - SwissVault.ai',
    expertConsensus: 'Expert Consensus',
    specialists: 'specialists',
    agreement: 'agreement',
  },
  es: {
    title: 'Nota SOAP',
    subtitle: 'Consulta de Salud HELIOS AI',
    generated: 'Generado',
    sessionId: 'ID de Sesión',
    patient: 'Paciente',
    age: 'Edad',
    sex: 'Sexo',
    chiefComplaint: 'Motivo de Consulta',
    triageLevel: 'Nivel de Triaje (ESI)',
    disposition: 'Disposición',
    subjective: 'Subjetivo',
    objective: 'Objetivo',
    assessment: 'Evaluación',
    plan: 'Plan',
    redFlags: 'Señales de Alerta',
    disclaimer: 'Este resumen generado por IA es solo para fines informativos y no constituye consejo médico. Consulte con un profesional de la salud licenciado.',
    footer: 'Generado por HELIOS AI Health Assistant - SwissVault.ai',
    expertConsensus: 'Consenso de Expertos',
    specialists: 'especialistas',
    agreement: 'acuerdo',
  },
  fr: {
    title: 'Note SOAP',
    subtitle: 'Consultation Santé HELIOS AI',
    generated: 'Généré',
    sessionId: 'ID de Session',
    patient: 'Patient',
    age: 'Âge',
    sex: 'Sexe',
    chiefComplaint: 'Motif de Consultation',
    triageLevel: 'Niveau de Triage (ESI)',
    disposition: 'Disposition',
    subjective: 'Subjectif',
    objective: 'Objectif',
    assessment: 'Évaluation',
    plan: 'Plan',
    redFlags: 'Signaux d\'Alerte',
    disclaimer: 'Ce résumé généré par l\'IA est uniquement à titre informatif et ne constitue pas un avis médical. Veuillez consulter un professionnel de la santé agréé.',
    footer: 'Généré par HELIOS AI Health Assistant - SwissVault.ai',
    expertConsensus: 'Consensus d\'Experts',
    specialists: 'spécialistes',
    agreement: 'accord',
  },
};

const ESI_COLORS: Record<number, { bg: string; text: string; label: string }> = {
  1: { bg: '#DC2626', text: '#FFFFFF', label: 'Immediate' },
  2: { bg: '#EA580C', text: '#FFFFFF', label: 'Emergent' },
  3: { bg: '#F59E0B', text: '#000000', label: 'Urgent' },
  4: { bg: '#10B981', text: '#FFFFFF', label: 'Less Urgent' },
  5: { bg: '#3B82F6', text: '#FFFFFF', label: 'Non-Urgent' },
};

function normalizeToArray(value: string | string[] | undefined): string[] {
  if (!value) return [];
  if (typeof value === 'string') return [value];
  return value;
}

function formatDate(dateString?: string, language: 'en' | 'es' | 'fr' = 'en'): string {
  if (!dateString) return new Date().toLocaleString(language);
  try {
    return new Date(dateString).toLocaleString(language, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return dateString;
  }
}

export async function generateSOAPPDF(
  soapData: SOAPData,
  sessionInfo: SessionInfo,
  options: PDFOptions = {}
): Promise<Blob> {
  const {
    includeDisclaimer = true,
    includeMetadata = true,
    language = 'en',
  } = options;

  const t = TRANSLATIONS[language] || TRANSLATIONS.en;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Helper to add new page if needed
  const checkPageBreak = (y: number, neededSpace: number = 30): number => {
    if (y + neededSpace > pageHeight - 40) {
      doc.addPage();
      return margin + 10;
    }
    return y;
  };

  // ========================================
  // HEADER
  // ========================================

  // Header background
  doc.setFillColor(29, 78, 95); // Teal brand color
  doc.rect(0, 0, pageWidth, 35, 'F');

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(t.title, margin, 18);

  // Subtitle
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(t.subtitle, margin, 28);

  // Date on right
  doc.setFontSize(9);
  doc.text(`${t.generated}: ${formatDate(sessionInfo.consultDate, language)}`, pageWidth - margin, 18, { align: 'right' });
  doc.text(`${t.sessionId}: ${sessionInfo.sessionId?.slice(0, 8) || 'N/A'}`, pageWidth - margin, 26, { align: 'right' });

  let y = 45;

  // ========================================
  // PATIENT INFO & TRIAGE
  // ========================================

  if (includeMetadata) {
    doc.setTextColor(0, 0, 0);

    // Patient info box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin, y, contentWidth, 28, 3, 3, 'F');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`${t.patient}:`, margin + 5, y + 8);

    doc.setFont('helvetica', 'normal');
    const patientText = `${t.age}: ${sessionInfo.patient?.age || 'N/A'} | ${t.sex}: ${sessionInfo.patient?.sex || 'N/A'}`;
    doc.text(patientText, margin + 45, y + 8);

    if (sessionInfo.chiefComplaint) {
      doc.setFont('helvetica', 'bold');
      doc.text(`${t.chiefComplaint}:`, margin + 5, y + 18);
      doc.setFont('helvetica', 'normal');
      const ccText = doc.splitTextToSize(sessionInfo.chiefComplaint, contentWidth - 80);
      doc.text(ccText[0], margin + 65, y + 18);
    }

    // Triage level badge
    if (sessionInfo.triageLevel && sessionInfo.triageLevel >= 1 && sessionInfo.triageLevel <= 5) {
      const esiConfig = ESI_COLORS[sessionInfo.triageLevel];
      const badgeX = pageWidth - margin - 45;

      doc.setFillColor(esiConfig.bg);
      doc.roundedRect(badgeX, y + 3, 40, 20, 3, 3, 'F');

      doc.setTextColor(esiConfig.text);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text(`ESI ${sessionInfo.triageLevel}`, badgeX + 20, y + 11, { align: 'center' });
      doc.setFontSize(6);
      doc.text(esiConfig.label, badgeX + 20, y + 18, { align: 'center' });
    }

    y += 35;

    // Expert consensus badge
    if (sessionInfo.expertCount && sessionInfo.expertCount > 0) {
      doc.setTextColor(100, 100, 100);
      doc.setFontSize(8);
      const consensusText = `${t.expertConsensus}: ${sessionInfo.expertCount} ${t.specialists}${sessionInfo.agreementScore ? ` | ${Math.round(sessionInfo.agreementScore * 100)}% ${t.agreement}` : ''}`;
      doc.text(consensusText, margin, y);
      y += 8;
    }
  }

  // ========================================
  // RED FLAGS (if any)
  // ========================================

  const redFlags = sessionInfo.redFlags || [];
  if (redFlags.length > 0) {
    y = checkPageBreak(y, 40);

    doc.setFillColor(254, 242, 242);
    doc.setDrawColor(220, 38, 38);
    doc.roundedRect(margin, y, contentWidth, 6 + redFlags.length * 6, 3, 3, 'FD');

    doc.setTextColor(185, 28, 28);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`⚠ ${t.redFlags}`, margin + 5, y + 5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    redFlags.forEach((flag, idx) => {
      doc.text(`• ${flag}`, margin + 10, y + 11 + idx * 5);
    });

    y += 12 + redFlags.length * 6;
  }

  y += 5;

  // ========================================
  // SOAP SECTIONS
  // ========================================

  const sections: Array<{ title: string; content: string[] }> = [
    { title: t.subjective, content: normalizeToArray(soapData.subjective) },
    { title: t.objective, content: normalizeToArray(soapData.objective) },
    { title: t.assessment, content: normalizeToArray(soapData.assessment) },
    { title: t.plan, content: normalizeToArray(soapData.plan) },
  ];

  const sectionColors = {
    [t.subjective]: { bg: '#EFF6FF', border: '#3B82F6' },
    [t.objective]: { bg: '#F0FDF4', border: '#22C55E' },
    [t.assessment]: { bg: '#FEF3C7', border: '#F59E0B' },
    [t.plan]: { bg: '#F3E8FF', border: '#A855F7' },
  };

  for (const section of sections) {
    if (section.content.length === 0) continue;

    y = checkPageBreak(y, 30);

    const colors = sectionColors[section.title] || { bg: '#F8FAFC', border: '#94A3B8' };

    // Section header
    doc.setFillColor(colors.border);
    doc.rect(margin, y, 4, 8, 'F');

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin + 8, y + 6);

    y += 12;

    // Section content
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(55, 65, 81);

    for (const item of section.content) {
      y = checkPageBreak(y, 15);

      const lines = doc.splitTextToSize(`• ${item}`, contentWidth - 10);
      doc.text(lines, margin + 8, y);
      y += lines.length * 5 + 3;
    }

    y += 8;
  }

  // ========================================
  // FOOTER / DISCLAIMER
  // ========================================

  if (includeDisclaimer) {
    // Go to bottom of last page
    y = pageHeight - 35;

    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);

    y += 5;

    doc.setFontSize(7);
    doc.setTextColor(128, 128, 128);
    doc.setFont('helvetica', 'italic');

    const disclaimerLines = doc.splitTextToSize(t.disclaimer, contentWidth);
    doc.text(disclaimerLines, margin, y);

    y += disclaimerLines.length * 3 + 5;

    doc.setFont('helvetica', 'normal');
    doc.text(t.footer, pageWidth / 2, y, { align: 'center' });
  }

  // ========================================
  // PAGE NUMBERS
  // ========================================

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  return doc.output('blob');
}

/**
 * Download SOAP note as PDF
 */
export async function downloadSOAPPDF(
  soapData: SOAPData,
  sessionInfo: SessionInfo,
  options: PDFOptions = {}
): Promise<void> {
  const blob = await generateSOAPPDF(soapData, sessionInfo, options);
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `HELIOS_SOAP_Note_${sessionInfo.sessionId?.slice(0, 8) || 'unknown'}_${new Date().toISOString().split('T')[0]}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

/**
 * Open SOAP note PDF in new tab
 */
export async function openSOAPPDF(
  soapData: SOAPData,
  sessionInfo: SessionInfo,
  options: PDFOptions = {}
): Promise<void> {
  const blob = await generateSOAPPDF(soapData, sessionInfo, options);
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
}

export default generateSOAPPDF;
