"""
PPTX presentation generator using python-pptx.

Generates PowerPoint presentations with:
- Title slide
- Content slides with bullet points
- Table slides
- Consistent formatting
"""

import os
from typing import Dict, Any
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

from .base import DocumentGenerator, DocumentContent


class PPTXGenerator(DocumentGenerator):
    """Generator for Microsoft PowerPoint (.pptx) presentations."""

    def __init__(self, content: DocumentContent):
        """
        Initialize PPTX generator.

        Args:
            content: DocumentContent with title and sections
        """
        super().__init__(content)
        self.presentation = Presentation()
        self.presentation.slide_width = Inches(10)
        self.presentation.slide_height = Inches(7.5)

    def get_format_name(self) -> str:
        """Return format name."""
        return "pptx"

    def validate_content(self) -> bool:
        """
        Validate content structure for PPTX generation.

        Returns:
            bool: True if valid

        Raises:
            ValueError: If content is invalid
        """
        if not self.content.title:
            raise ValueError("Presentation title is required")

        if not self.content.sections:
            raise ValueError("At least one section is required")

        for idx, section in enumerate(self.content.sections):
            if "heading" not in section:
                raise ValueError(f"Section {idx} missing 'heading' field")

        return True

    def generate(self, output_path: str) -> str:
        """
        Generate PPTX presentation.

        Args:
            output_path: Path to save the presentation

        Returns:
            str: Path to generated presentation
        """
        self.validate_content()

        # Add title slide
        self._add_title_slide()

        # Add content slides
        for section in self.content.sections:
            self._add_content_slide(section)

        # Save presentation
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        self.presentation.save(output_path)

        # Update metadata
        file_size = os.path.getsize(output_path)
        page_count = len(self.presentation.slides)
        self.update_metadata(file_size=file_size, page_count=page_count)

        return output_path

    def _add_title_slide(self):
        """Add title slide to presentation."""
        title_slide_layout = self.presentation.slide_layouts[0]
        slide = self.presentation.slides.add_slide(title_slide_layout)

        # Set title
        title = slide.shapes.title
        title.text = self.content.title

        # Set subtitle if metadata present
        if len(slide.placeholders) > 1:
            subtitle = slide.placeholders[1]
            if self.content.metadata:
                author = self.content.metadata.get("author", "Swiss AI Vault Agent")
                created_at = self.content.metadata.get("created_at", "")
                subtitle.text = f"By {author}\n{created_at}"
            else:
                subtitle.text = "Generated by Swiss AI Vault Agent"

    def _add_content_slide(self, section: Dict[str, Any]):
        """
        Add a content slide to the presentation.

        Args:
            section: Section data with heading and content
        """
        content_type = section.get("type", "text")

        if content_type == "table":
            self._add_table_slide(section)
        else:
            self._add_bullet_slide(section)

    def _add_bullet_slide(self, section: Dict[str, Any]):
        """
        Add a bullet point slide.

        Args:
            section: Section data
        """
        # Use title and content layout
        bullet_slide_layout = self.presentation.slide_layouts[1]
        slide = self.presentation.slides.add_slide(bullet_slide_layout)

        # Set title
        title = slide.shapes.title
        title.text = section.get("heading", "Content")

        # Add content
        content_placeholder = slide.placeholders[1]
        text_frame = content_placeholder.text_frame
        text_frame.clear()

        content_type = section.get("type", "text")

        if content_type in ["bullet_list", "numbered_list"]:
            items = section.get("items", [])
            for idx, item in enumerate(items):
                p = text_frame.add_paragraph()
                p.text = str(item)
                p.level = 0
                if idx == 0:
                    # First paragraph already exists
                    text_frame.paragraphs[0].text = str(item)

        elif content_type == "text":
            content = section.get("content", "")
            if isinstance(content, list):
                for idx, item in enumerate(content):
                    if idx == 0:
                        text_frame.text = str(item)
                    else:
                        p = text_frame.add_paragraph()
                        p.text = str(item)
                        p.level = 0
            else:
                text_frame.text = str(content)

        elif content_type == "code":
            code_content = section.get("content", "")
            text_frame.text = code_content
            for paragraph in text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.name = 'Courier New'
                    run.font.size = Pt(10)

    def _add_table_slide(self, section: Dict[str, Any]):
        """
        Add a table slide.

        Args:
            section: Section data with table configuration
        """
        headers = section.get("headers", [])
        rows = section.get("rows", [])

        if not headers or not rows:
            return

        # Use blank layout for table
        blank_slide_layout = self.presentation.slide_layouts[6]
        slide = self.presentation.slides.add_slide(blank_slide_layout)

        # Add title
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.5),
            Inches(9), Inches(0.5)
        )
        title_frame = title_box.text_frame
        title_frame.text = section.get("heading", "Table")
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(28)
        title_para.font.bold = True

        # Calculate table dimensions
        num_rows = len(rows) + 1  # +1 for header
        num_cols = len(headers)

        # Add table
        table_shape = slide.shapes.add_table(
            num_rows, num_cols,
            Inches(0.5), Inches(1.5),
            Inches(9), Inches(5)
        )
        table = table_shape.table

        # Set column widths evenly
        col_width = Inches(9) / num_cols
        for col_idx in range(num_cols):
            table.columns[col_idx].width = col_width

        # Add headers
        for col_idx, header in enumerate(headers):
            cell = table.cell(0, col_idx)
            cell.text = str(header)
            # Format header
            for paragraph in cell.text_frame.paragraphs:
                paragraph.font.bold = True
                paragraph.font.size = Pt(12)
            # Header background color
            cell.fill.solid()
            cell.fill.fore_color.rgb = RGBColor(0, 112, 192)

        # Add data rows
        for row_idx, row_data in enumerate(rows, start=1):
            for col_idx, cell_value in enumerate(row_data):
                if col_idx < num_cols:
                    cell = table.cell(row_idx, col_idx)
                    cell.text = str(cell_value)
                    # Format data cells
                    for paragraph in cell.text_frame.paragraphs:
                        paragraph.font.size = Pt(11)
