/**
 * VoiceConsultation Component - Hume EVI Speech-to-Speech Interface
 * Provides empathetic voice consultations with emotion detection
 */

import { useState, useEffect } from 'react';
import { useHumeEVI, HumeMessage } from '@/hooks/helios/useHumeEVI';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { 
  Mic, 
  MicOff, 
  Phone, 
  PhoneOff, 
  Volume2, 
  Download,
  FileText,
  AlertCircle,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import { cn } from '@/lib/utils';

interface VoiceConsultationProps {
  sessionId: string;
  specialty: string;
  language: string;
  onComplete?: (summary: Record<string, unknown>) => void;
}

// Emotion indicator colors
const EMOTION_COLORS: Record<string, string> = {
  Anxiety: 'text-yellow-500',
  Fear: 'text-orange-500',
  Sadness: 'text-blue-500',
  Joy: 'text-green-500',
  Anger: 'text-red-500',
  Neutral: 'text-muted-foreground',
  Distress: 'text-red-600',
  Pain: 'text-red-500',
  Confusion: 'text-purple-500',
  Calmness: 'text-emerald-500',
};

export function VoiceConsultation({ 
  sessionId, 
  specialty, 
  language,
  onComplete 
}: VoiceConsultationProps) {
  const [showTranscript, setShowTranscript] = useState(false);
  
  const {
    isConnected,
    isListening,
    isSpeaking,
    transcript,
    currentEmotion,
    connect,
    disconnect,
    toggleListening,
    endConsultation,
    saveTranscript,
  } = useHumeEVI({
    sessionId,
    specialty,
    language,
    onConsultationEnd: onComplete,
  });

  // Download transcript as markdown
  const downloadTranscript = () => {
    if (transcript.length === 0) return;
    
    const lines = [
      `# HELIOS Voice Consultation`,
      `**Date:** ${new Date().toLocaleString()}`,
      `**Specialty:** ${specialty}`,
      `**Language:** ${language}`,
      `**Session ID:** ${sessionId}`,
      '',
      '---',
      '',
      '## Conversation',
      '',
    ];
    
    transcript.forEach((msg) => {
      const speaker = msg.type === 'user_message' ? '**You:**' : '**HELIOS:**';
      lines.push(`${speaker} ${msg.content || ''}`);
      
      if (msg.emotion && msg.emotion.length > 0) {
        const topEmotion = msg.emotion[0];
        lines.push(`*Detected emotion: ${topEmotion.name} (${(topEmotion.score * 100).toFixed(0)}%)*`);
      }
      lines.push('');
    });
    
    lines.push('---');
    lines.push('');
    lines.push('*This transcript was generated by HELIOS AI Health Assistant.*');
    lines.push('*For informational purposes only. Not a substitute for professional medical advice.*');
    
    const content = lines.join('\n');
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `helios-voice-consult-${sessionId}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      {/* Connection Status */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div 
            className={cn(
              "w-2 h-2 rounded-full",
              isConnected ? "bg-green-500" : "bg-muted"
            )} 
          />
          <span className="text-sm text-muted-foreground">
            {isConnected ? 'Voice consultation active' : 'Voice consultation inactive'}
          </span>
        </div>
        
        {currentEmotion && (
          <span className={cn("text-sm font-medium", EMOTION_COLORS[currentEmotion] || EMOTION_COLORS.Neutral)}>
            Detected: {currentEmotion}
          </span>
        )}
      </div>

      {/* Main Controls */}
      <Card className="p-6">
        <div className="flex flex-col items-center space-y-6">
          {/* Voice Visualization */}
          <div className="relative w-32 h-32 flex items-center justify-center">
            <div 
              className={cn(
                "absolute inset-0 rounded-full transition-all duration-300",
                isSpeaking && "bg-teal-100 animate-pulse",
                isListening && !isSpeaking && "bg-blue-100 animate-pulse"
              )}
            />
            
            {isSpeaking ? (
              <Volume2 className="w-16 h-16 text-teal-600 relative z-10 animate-bounce" />
            ) : isListening ? (
              <Mic className="w-16 h-16 text-blue-600 relative z-10" />
            ) : (
              <MicOff className="w-16 h-16 text-muted-foreground relative z-10" />
            )}
          </div>

          {/* Status Text */}
          <p className="text-center text-muted-foreground">
            {isSpeaking 
              ? "HELIOS is speaking..." 
              : isListening 
                ? "Listening... Speak now" 
                : "Click microphone to speak"
            }
          </p>

          {/* Control Buttons */}
          <div className="flex items-center gap-4">
            {!isConnected ? (
              <Button 
                onClick={connect} 
                className="bg-teal-600 hover:bg-teal-700"
              >
                <Phone className="w-4 h-4 mr-2" />
                Start Voice Consultation
              </Button>
            ) : (
              <>
                <Button
                  variant={isListening ? "destructive" : "default"}
                  size="lg"
                  className="rounded-full w-16 h-16"
                  onClick={toggleListening}
                >
                  {isListening ? (
                    <MicOff className="w-6 h-6" />
                  ) : (
                    <Mic className="w-6 h-6" />
                  )}
                </Button>
                
                <Button 
                  variant="outline" 
                  onClick={endConsultation}
                >
                  <PhoneOff className="w-4 h-4 mr-2" />
                  End Consultation
                </Button>
              </>
            )}
          </div>
        </div>
      </Card>

      {/* Live Transcript */}
      {isConnected && (
        <Card className="p-4">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4 text-muted-foreground" />
              <span className="text-sm font-medium">Live Transcript</span>
            </div>
            
            <div className="flex items-center gap-2">
              {transcript.length > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={downloadTranscript}
                >
                  <Download className="w-4 h-4 mr-1" />
                  Download
                </Button>
              )}
              
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowTranscript(!showTranscript)}
              >
                {showTranscript ? (
                  <>Hide <ChevronUp className="w-4 h-4 ml-1" /></>
                ) : (
                  <>Show <ChevronDown className="w-4 h-4 ml-1" /></>
                )}
              </Button>
            </div>
          </div>

          {showTranscript && (
            <div className="max-h-60 overflow-y-auto space-y-2 mt-2">
              {transcript.length === 0 ? (
                <p className="text-sm text-muted-foreground text-center py-4">
                  Conversation will appear here...
                </p>
              ) : (
                transcript.map((msg, i) => (
                  <div 
                    key={i} 
                    className={cn(
                      "p-2 rounded text-sm",
                      msg.type === 'user_message' 
                        ? "bg-blue-50 ml-4" 
                        : "bg-teal-50 mr-4"
                    )}
                  >
                    <span className="font-medium">
                      {msg.type === 'user_message' ? 'You' : 'HELIOS'}
                    </span>
                    <p className="mt-1">{msg.content}</p>
                    
                    {msg.emotion && msg.emotion.length > 0 && (
                      <span className={cn(
                        "text-xs mt-1 block",
                        EMOTION_COLORS[msg.emotion[0].name] || EMOTION_COLORS.Neutral
                      )}>
                        {msg.emotion[0].name} ({(msg.emotion[0].score * 100).toFixed(0)}%)
                      </span>
                    )}
                  </div>
                ))
              )}
            </div>
          )}
        </Card>
      )}

      {/* Emergency Warning */}
      <div className="flex items-start gap-2 p-3 bg-amber-50 rounded-lg text-sm text-amber-800">
        <AlertCircle className="w-4 h-4 mt-0.5 flex-shrink-0" />
        <p>
          <strong>Emergency?</strong> If you're experiencing chest pain, difficulty breathing, 
          or other emergency symptoms, please call <strong>911</strong> immediately.
        </p>
      </div>
    </div>
  );
}
